//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ChClassFactory : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ChClassFactory(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChClassFactory obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ChClassFactory() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          chronoPINVOKE.delete_ChClassFactory(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ChClassFactory() : this(chronoPINVOKE.new_ChClassFactory(), true) {
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void ClassRegister(string keyName, SWIGTYPE_p_chrono__ChClassRegistrationBase mregistration) {
    chronoPINVOKE.ChClassFactory_ClassRegister(keyName, SWIGTYPE_p_chrono__ChClassRegistrationBase.getCPtr(mregistration));
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void ClassUnregister(string keyName) {
    chronoPINVOKE.ChClassFactory_ClassUnregister(keyName);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static bool IsClassRegistered(string keyName) {
    bool ret = chronoPINVOKE.ChClassFactory_IsClassRegistered__SWIG_0(keyName);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool IsClassRegistered(SWIGTYPE_p_std__type_index mtypeid) {
    bool ret = chronoPINVOKE.ChClassFactory_IsClassRegistered__SWIG_1(SWIGTYPE_p_std__type_index.getCPtr(mtypeid));
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_chrono__ChClassRegistrationBase GetClass(string keyName) {
    global::System.IntPtr cPtr = chronoPINVOKE.ChClassFactory_GetClass(keyName);
    SWIGTYPE_p_chrono__ChClassRegistrationBase ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_chrono__ChClassRegistrationBase(cPtr, false);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_std__string GetClassTagName(SWIGTYPE_p_std__type_index mtypeid) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(chronoPINVOKE.ChClassFactory_GetClassTagName(SWIGTYPE_p_std__type_index.getCPtr(mtypeid)), false);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
