//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ChLoaderUVdistributed : ChLoaderUV {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal ChLoaderUVdistributed(global::System.IntPtr cPtr, bool cMemoryOwn) : base(chronoPINVOKE.ChLoaderUVdistributed_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChLoaderUVdistributed obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          chronoPINVOKE.delete_ChLoaderUVdistributed(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ChLoaderUVdistributed(ChLoadableUV mloadable) : this(chronoPINVOKE.new_ChLoaderUVdistributed(ChLoadableUV.getCPtr(mloadable)), true) {
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public virtual int GetIntegrationPointsU() {
    int ret = chronoPINVOKE.ChLoaderUVdistributed_GetIntegrationPointsU(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetIntegrationPointsV() {
    int ret = chronoPINVOKE.ChLoaderUVdistributed_GetIntegrationPointsV(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void ComputeQ(ChVectorDynamicd state_x, ChVectorDynamicd state_w) {
    if (SwigDerivedClassHasMethod("ComputeQ", swigMethodTypes0)) chronoPINVOKE.ChLoaderUVdistributed_ComputeQSwigExplicitChLoaderUVdistributed(swigCPtr, ChVectorDynamicd.getCPtr(state_x), ChVectorDynamicd.getCPtr(state_w)); else chronoPINVOKE.ChLoaderUVdistributed_ComputeQ(swigCPtr, ChVectorDynamicd.getCPtr(state_x), ChVectorDynamicd.getCPtr(state_w));
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("ComputeQ", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateChLoaderUVdistributed_0(SwigDirectorMethodComputeQ);
    if (SwigDerivedClassHasMethod("GetLoadable", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateChLoaderUVdistributed_1(SwigDirectorMethodGetLoadable);
    if (SwigDerivedClassHasMethod("IsStiff", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateChLoaderUVdistributed_2(SwigDirectorMethodIsStiff);
    if (SwigDerivedClassHasMethod("ComputeF", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateChLoaderUVdistributed_3(SwigDirectorMethodComputeF);
    if (SwigDerivedClassHasMethod("GetIntegrationPointsU", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateChLoaderUVdistributed_4(SwigDirectorMethodGetIntegrationPointsU);
    if (SwigDerivedClassHasMethod("GetIntegrationPointsV", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateChLoaderUVdistributed_5(SwigDirectorMethodGetIntegrationPointsV);
    chronoPINVOKE.ChLoaderUVdistributed_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(ChLoaderUVdistributed));
    return hasDerivedMethod;
  }

  private void SwigDirectorMethodComputeQ(global::System.IntPtr state_x, global::System.IntPtr state_w) {
    ComputeQ((state_x == global::System.IntPtr.Zero) ? null : new ChVectorDynamicd(state_x, false), (state_w == global::System.IntPtr.Zero) ? null : new ChVectorDynamicd(state_w, false));
  }

  private global::System.IntPtr SwigDirectorMethodGetLoadable() {
    return ChLoadable.getCPtr(GetLoadable()).Handle;
  }

  private bool SwigDirectorMethodIsStiff() {
    return IsStiff();
  }

  private void SwigDirectorMethodComputeF(double U, double V, global::System.IntPtr F, global::System.IntPtr state_x, global::System.IntPtr state_w) {
    ComputeF(U, V, new ChVectorDynamicd(F, false), (state_x == global::System.IntPtr.Zero) ? null : new ChVectorDynamicd(state_x, false), (state_w == global::System.IntPtr.Zero) ? null : new ChVectorDynamicd(state_w, false));
  }

  private int SwigDirectorMethodGetIntegrationPointsU() {
    return GetIntegrationPointsU();
  }

  private int SwigDirectorMethodGetIntegrationPointsV() {
    return GetIntegrationPointsV();
  }

  public delegate void SwigDelegateChLoaderUVdistributed_0(global::System.IntPtr state_x, global::System.IntPtr state_w);
  public delegate global::System.IntPtr SwigDelegateChLoaderUVdistributed_1();
  public delegate bool SwigDelegateChLoaderUVdistributed_2();
  public delegate void SwigDelegateChLoaderUVdistributed_3(double U, double V, global::System.IntPtr F, global::System.IntPtr state_x, global::System.IntPtr state_w);
  public delegate int SwigDelegateChLoaderUVdistributed_4();
  public delegate int SwigDelegateChLoaderUVdistributed_5();

  private SwigDelegateChLoaderUVdistributed_0 swigDelegate0;
  private SwigDelegateChLoaderUVdistributed_1 swigDelegate1;
  private SwigDelegateChLoaderUVdistributed_2 swigDelegate2;
  private SwigDelegateChLoaderUVdistributed_3 swigDelegate3;
  private SwigDelegateChLoaderUVdistributed_4 swigDelegate4;
  private SwigDelegateChLoaderUVdistributed_5 swigDelegate5;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(ChVectorDynamicd), typeof(ChVectorDynamicd) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes3 = new global::System.Type[] { typeof(double), typeof(double), typeof(ChVectorDynamicd), typeof(ChVectorDynamicd), typeof(ChVectorDynamicd) };
  private static global::System.Type[] swigMethodTypes4 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes5 = new global::System.Type[] {  };
}
