/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_chrono_WRAP_H_
#define SWIG_chrono_WRAP_H_

class SwigDirector_BroadphaseCallback : public chrono::ChCollisionSystem::BroadphaseCallback, public Swig::Director {

public:
    SwigDirector_BroadphaseCallback();
    virtual ~SwigDirector_BroadphaseCallback();
    virtual bool OnBroadphase(chrono::ChCollisionModel *modelA, chrono::ChCollisionModel *modelB);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnBroadphase);

private:
    SWIG_Callback0_t swig_callbackOnBroadphase;
    void swig_init_callbacks();
};

class SwigDirector_NarrowphaseCallback : public chrono::ChCollisionSystem::NarrowphaseCallback, public Swig::Director {

public:
    SwigDirector_NarrowphaseCallback();
    virtual ~SwigDirector_NarrowphaseCallback();
    virtual bool OnNarrowphase(chrono::ChCollisionInfo &contactinfo);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnNarrowphase);

private:
    SWIG_Callback0_t swig_callbackOnNarrowphase;
    void swig_init_callbacks();
};

class SwigDirector_VisualizationCallback : public chrono::ChCollisionSystem::VisualizationCallback, public Swig::Director {

public:
    SwigDirector_VisualizationCallback();
    virtual ~SwigDirector_VisualizationCallback();
    virtual void DrawLine(chrono::ChVector3d const &from, chrono::ChVector3d const &to, ChColor const &color);
    virtual double GetNormalScale() const;

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *);
    typedef double (SWIGSTDCALL* SWIG_Callback1_t)();
    void swig_connect_director(SWIG_Callback0_t callbackDrawLine, SWIG_Callback1_t callbackGetNormalScale);

private:
    SWIG_Callback0_t swig_callbackDrawLine;
    SWIG_Callback1_t swig_callbackGetNormalScale;
    void swig_init_callbacks();
};

class SwigDirector_ChFunction : public chrono::ChFunction, public Swig::Director {

public:
    SwigDirector_ChFunction();
    SwigDirector_ChFunction(chrono::ChFunction const &other);
    virtual ~SwigDirector_ChFunction();
    virtual chrono::ChFunction *Clone() const;
    virtual chrono::ChFunction::Type GetType() const;
    virtual double GetVal(double x) const;
    virtual double GetDer(double x) const;
    virtual double GetDer2(double x) const;
    virtual double GetDer3(double x) const;
    virtual double GetDerN(double x, int der_order) const;
    virtual double GetWeight(double x) const;
    virtual void Update(double x);
    virtual double GetMax(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetMin(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetMean(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetSquaredMean(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetIntegral(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetPositiveAccelerationCoeff() const;
    virtual double GetNegativeAccelerationCoeff() const;
    virtual double GetVelocityCoefficient() const;
    virtual void OutputToASCIIFile(std::ostream &file, double xmin, double xmax, int samples, char delimiter);
    virtual chrono::ChMatrixDynamic< > SampleUpToDerN(double xmin, double xmax, double step, int derN = 0);
    virtual void ArchiveOut(chrono::ChArchiveOut &archive_out);
    virtual void ArchiveIn(chrono::ChArchiveIn &archive_in);

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback3_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback4_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback5_t)(double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback6_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback8_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback9_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback10_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback11_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback12_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback13_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback14_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback15_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(void *, double, double, int, char);
    typedef void * (SWIGSTDCALL* SWIG_Callback17_t)(double, double, double, int);
    typedef void * (SWIGSTDCALL* SWIG_Callback18_t)(double, double, double);
    typedef void (SWIGSTDCALL* SWIG_Callback19_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback20_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackGetFunctionType, SWIG_Callback1_t callbackGetVal, SWIG_Callback2_t callbackGetDer, SWIG_Callback3_t callbackGetDer2, SWIG_Callback4_t callbackGetDer3, SWIG_Callback5_t callbackGetDerN, SWIG_Callback6_t callbackGetWeight, SWIG_Callback7_t callbackUpdate, SWIG_Callback8_t callbackGetMax, SWIG_Callback9_t callbackGetMin, SWIG_Callback10_t callbackGetMean, SWIG_Callback11_t callbackGetSquaredMean, SWIG_Callback12_t callbackGetIntegral, SWIG_Callback13_t callbackGetPositiveAccelerationCoeff, SWIG_Callback14_t callbackGetNegativeAccelerationCoeff, SWIG_Callback15_t callbackGetVelocityCoefficient, SWIG_Callback16_t callbackOutputToASCIIFile, SWIG_Callback17_t callbackSampleUpToDerN__SWIG_0, SWIG_Callback18_t callbackSampleUpToDerN__SWIG_1, SWIG_Callback19_t callbackArchiveOut, SWIG_Callback20_t callbackArchiveIn);

private:
    SWIG_Callback0_t swig_callbackGetFunctionType;
    SWIG_Callback1_t swig_callbackGetVal;
    SWIG_Callback2_t swig_callbackGetDer;
    SWIG_Callback3_t swig_callbackGetDer2;
    SWIG_Callback4_t swig_callbackGetDer3;
    SWIG_Callback5_t swig_callbackGetDerN;
    SWIG_Callback6_t swig_callbackGetWeight;
    SWIG_Callback7_t swig_callbackUpdate;
    SWIG_Callback8_t swig_callbackGetMax;
    SWIG_Callback9_t swig_callbackGetMin;
    SWIG_Callback10_t swig_callbackGetMean;
    SWIG_Callback11_t swig_callbackGetSquaredMean;
    SWIG_Callback12_t swig_callbackGetIntegral;
    SWIG_Callback13_t swig_callbackGetPositiveAccelerationCoeff;
    SWIG_Callback14_t swig_callbackGetNegativeAccelerationCoeff;
    SWIG_Callback15_t swig_callbackGetVelocityCoefficient;
    SWIG_Callback16_t swig_callbackOutputToASCIIFile;
    SWIG_Callback17_t swig_callbackSampleUpToDerN__SWIG_0;
    SWIG_Callback18_t swig_callbackSampleUpToDerN__SWIG_1;
    SWIG_Callback19_t swig_callbackArchiveOut;
    SWIG_Callback20_t swig_callbackArchiveIn;
    void swig_init_callbacks();
};

class SwigDirector_ChFunctionSetpoint : public chrono::ChFunctionSetpoint, public Swig::Director {

public:
    SwigDirector_ChFunctionSetpoint();
    SwigDirector_ChFunctionSetpoint(chrono::ChFunctionSetpoint const &other);
    virtual ~SwigDirector_ChFunctionSetpoint();
    virtual chrono::ChFunctionSetpoint *Clone() const;
    virtual chrono::ChFunction::Type GetType() const;
    virtual double GetVal(double x) const;
    virtual double GetDer(double x) const;
    virtual double GetDer2(double x) const;
    virtual double GetDer3(double x) const;
    virtual double GetDerN(double x, int der_order) const;
    virtual double GetWeight(double x) const;
    virtual void Update(double x);
    virtual double GetMax(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetMin(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetMean(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetSquaredMean(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetIntegral(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetPositiveAccelerationCoeff() const;
    virtual double GetNegativeAccelerationCoeff() const;
    virtual double GetVelocityCoefficient() const;
    virtual void OutputToASCIIFile(std::ostream &file, double xmin, double xmax, int samples, char delimiter);
    virtual chrono::ChMatrixDynamic< > SampleUpToDerN(double xmin, double xmax, double step, int derN = 0);
    virtual void ArchiveOut(chrono::ChArchiveOut &archive_out);
    virtual void ArchiveIn(chrono::ChArchiveIn &archive_in);
    virtual void SetSetpoint(double setpoint, double x);
    virtual void SetSetpointAndDerivatives(double setpoint, double setpoint_dx, double setpoint_dxdx);

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback3_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback4_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback5_t)(double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback6_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback8_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback9_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback10_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback11_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback12_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback13_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback14_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback15_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(void *, double, double, int, char);
    typedef void * (SWIGSTDCALL* SWIG_Callback17_t)(double, double, double, int);
    typedef void * (SWIGSTDCALL* SWIG_Callback18_t)(double, double, double);
    typedef void (SWIGSTDCALL* SWIG_Callback19_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback20_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback21_t)(double, double);
    typedef void (SWIGSTDCALL* SWIG_Callback22_t)(double, double, double);
    void swig_connect_director(SWIG_Callback0_t callbackGetFunctionType, SWIG_Callback1_t callbackGetVal, SWIG_Callback2_t callbackGetDer, SWIG_Callback3_t callbackGetDer2, SWIG_Callback4_t callbackGetDer3, SWIG_Callback5_t callbackGetDerN, SWIG_Callback6_t callbackGetWeight, SWIG_Callback7_t callbackUpdate, SWIG_Callback8_t callbackGetMax, SWIG_Callback9_t callbackGetMin, SWIG_Callback10_t callbackGetMean, SWIG_Callback11_t callbackGetSquaredMean, SWIG_Callback12_t callbackGetIntegral, SWIG_Callback13_t callbackGetPositiveAccelerationCoeff, SWIG_Callback14_t callbackGetNegativeAccelerationCoeff, SWIG_Callback15_t callbackGetVelocityCoefficient, SWIG_Callback16_t callbackOutputToASCIIFile, SWIG_Callback17_t callbackSampleUpToDerN__SWIG_0, SWIG_Callback18_t callbackSampleUpToDerN__SWIG_1, SWIG_Callback19_t callbackArchiveOut, SWIG_Callback20_t callbackArchiveIn, SWIG_Callback21_t callbackSetSetpoint, SWIG_Callback22_t callbackSetSetpointAndDerivatives);

private:
    SWIG_Callback0_t swig_callbackGetFunctionType;
    SWIG_Callback1_t swig_callbackGetVal;
    SWIG_Callback2_t swig_callbackGetDer;
    SWIG_Callback3_t swig_callbackGetDer2;
    SWIG_Callback4_t swig_callbackGetDer3;
    SWIG_Callback5_t swig_callbackGetDerN;
    SWIG_Callback6_t swig_callbackGetWeight;
    SWIG_Callback7_t swig_callbackUpdate;
    SWIG_Callback8_t swig_callbackGetMax;
    SWIG_Callback9_t swig_callbackGetMin;
    SWIG_Callback10_t swig_callbackGetMean;
    SWIG_Callback11_t swig_callbackGetSquaredMean;
    SWIG_Callback12_t swig_callbackGetIntegral;
    SWIG_Callback13_t swig_callbackGetPositiveAccelerationCoeff;
    SWIG_Callback14_t swig_callbackGetNegativeAccelerationCoeff;
    SWIG_Callback15_t swig_callbackGetVelocityCoefficient;
    SWIG_Callback16_t swig_callbackOutputToASCIIFile;
    SWIG_Callback17_t swig_callbackSampleUpToDerN__SWIG_0;
    SWIG_Callback18_t swig_callbackSampleUpToDerN__SWIG_1;
    SWIG_Callback19_t swig_callbackArchiveOut;
    SWIG_Callback20_t swig_callbackArchiveIn;
    SWIG_Callback21_t swig_callbackSetSetpoint;
    SWIG_Callback22_t swig_callbackSetSetpointAndDerivatives;
    void swig_init_callbacks();
};

class SwigDirector_ChFunctionSetpointCallback : public chrono::ChFunctionSetpointCallback, public Swig::Director {

public:
    SwigDirector_ChFunctionSetpointCallback();
    SwigDirector_ChFunctionSetpointCallback(chrono::ChFunctionSetpointCallback const &other);
    virtual ~SwigDirector_ChFunctionSetpointCallback();
    virtual chrono::ChFunctionSetpoint *Clone() const;
    virtual chrono::ChFunction::Type GetType() const;
    virtual double GetVal(double x) const;
    virtual double GetDer(double x) const;
    virtual double GetDer2(double x) const;
    virtual double GetDer3(double x) const;
    virtual double GetDerN(double x, int der_order) const;
    virtual double GetWeight(double x) const;
    virtual void Update(double x);
    virtual double GetMax(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetMin(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetMean(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetSquaredMean(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetIntegral(double xmin, double xmax, double sampling_step, int der_order) const;
    virtual double GetPositiveAccelerationCoeff() const;
    virtual double GetNegativeAccelerationCoeff() const;
    virtual double GetVelocityCoefficient() const;
    virtual void OutputToASCIIFile(std::ostream &file, double xmin, double xmax, int samples, char delimiter);
    virtual chrono::ChMatrixDynamic< > SampleUpToDerN(double xmin, double xmax, double step, int derN = 0);
    virtual void ArchiveOut(chrono::ChArchiveOut &archive_out);
    virtual void ArchiveIn(chrono::ChArchiveIn &archive_in);
    virtual void SetSetpoint(double setpoint, double x);
    virtual void SetSetpointAndDerivatives(double setpoint, double setpoint_dx, double setpoint_dxdx);
    virtual double SetpointCallback(double x);

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback3_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback4_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback5_t)(double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback6_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback8_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback9_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback10_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback11_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback12_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback13_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback14_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback15_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(void *, double, double, int, char);
    typedef void * (SWIGSTDCALL* SWIG_Callback17_t)(double, double, double, int);
    typedef void * (SWIGSTDCALL* SWIG_Callback18_t)(double, double, double);
    typedef void (SWIGSTDCALL* SWIG_Callback19_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback20_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback21_t)(double, double);
    typedef void (SWIGSTDCALL* SWIG_Callback22_t)(double, double, double);
    typedef double (SWIGSTDCALL* SWIG_Callback23_t)(double);
    void swig_connect_director(SWIG_Callback0_t callbackGetFunctionType, SWIG_Callback1_t callbackGetVal, SWIG_Callback2_t callbackGetDer, SWIG_Callback3_t callbackGetDer2, SWIG_Callback4_t callbackGetDer3, SWIG_Callback5_t callbackGetDerN, SWIG_Callback6_t callbackGetWeight, SWIG_Callback7_t callbackUpdate, SWIG_Callback8_t callbackGetMax, SWIG_Callback9_t callbackGetMin, SWIG_Callback10_t callbackGetMean, SWIG_Callback11_t callbackGetSquaredMean, SWIG_Callback12_t callbackGetIntegral, SWIG_Callback13_t callbackGetPositiveAccelerationCoeff, SWIG_Callback14_t callbackGetNegativeAccelerationCoeff, SWIG_Callback15_t callbackGetVelocityCoefficient, SWIG_Callback16_t callbackOutputToASCIIFile, SWIG_Callback17_t callbackSampleUpToDerN__SWIG_0, SWIG_Callback18_t callbackSampleUpToDerN__SWIG_1, SWIG_Callback19_t callbackArchiveOut, SWIG_Callback20_t callbackArchiveIn, SWIG_Callback21_t callbackSetSetpoint, SWIG_Callback22_t callbackSetSetpointAndDerivatives, SWIG_Callback23_t callbackSetpointCallback);

private:
    SWIG_Callback0_t swig_callbackGetFunctionType;
    SWIG_Callback1_t swig_callbackGetVal;
    SWIG_Callback2_t swig_callbackGetDer;
    SWIG_Callback3_t swig_callbackGetDer2;
    SWIG_Callback4_t swig_callbackGetDer3;
    SWIG_Callback5_t swig_callbackGetDerN;
    SWIG_Callback6_t swig_callbackGetWeight;
    SWIG_Callback7_t swig_callbackUpdate;
    SWIG_Callback8_t swig_callbackGetMax;
    SWIG_Callback9_t swig_callbackGetMin;
    SWIG_Callback10_t swig_callbackGetMean;
    SWIG_Callback11_t swig_callbackGetSquaredMean;
    SWIG_Callback12_t swig_callbackGetIntegral;
    SWIG_Callback13_t swig_callbackGetPositiveAccelerationCoeff;
    SWIG_Callback14_t swig_callbackGetNegativeAccelerationCoeff;
    SWIG_Callback15_t swig_callbackGetVelocityCoefficient;
    SWIG_Callback16_t swig_callbackOutputToASCIIFile;
    SWIG_Callback17_t swig_callbackSampleUpToDerN__SWIG_0;
    SWIG_Callback18_t swig_callbackSampleUpToDerN__SWIG_1;
    SWIG_Callback19_t swig_callbackArchiveOut;
    SWIG_Callback20_t swig_callbackArchiveIn;
    SWIG_Callback21_t swig_callbackSetSetpoint;
    SWIG_Callback22_t swig_callbackSetSetpointAndDerivatives;
    SWIG_Callback23_t swig_callbackSetpointCallback;
    void swig_init_callbacks();
};

class SwigDirector_ChFunctionPosition : public chrono::ChFunctionPosition, public Swig::Director {

public:
    SwigDirector_ChFunctionPosition();
    SwigDirector_ChFunctionPosition(chrono::ChFunctionPosition const &other);
    virtual ~SwigDirector_ChFunctionPosition();
    virtual chrono::ChFunctionPosition *Clone() const;
    virtual chrono::ChVector3d GetPos(double s) const;
    virtual chrono::ChVector3d GetLinVel(double s) const;
    virtual chrono::ChVector3d GetLinAcc(double s) const;
    virtual void Update(double t);
    virtual void ArchiveOut(chrono::ChArchiveOut &archive_out);
    virtual void ArchiveIn(chrono::ChArchiveIn &archive_in);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackGetPos, SWIG_Callback1_t callbackGetLinVel, SWIG_Callback2_t callbackGetLinAcc, SWIG_Callback3_t callbackUpdate, SWIG_Callback4_t callbackArchiveOut, SWIG_Callback5_t callbackArchiveIn);

private:
    SWIG_Callback0_t swig_callbackGetPos;
    SWIG_Callback1_t swig_callbackGetLinVel;
    SWIG_Callback2_t swig_callbackGetLinAcc;
    SWIG_Callback3_t swig_callbackUpdate;
    SWIG_Callback4_t swig_callbackArchiveOut;
    SWIG_Callback5_t swig_callbackArchiveIn;
    void swig_init_callbacks();
};

class SwigDirector_ChFunctionPositionSetpoint : public chrono::ChFunctionPositionSetpoint, public Swig::Director {

public:
    SwigDirector_ChFunctionPositionSetpoint();
    SwigDirector_ChFunctionPositionSetpoint(chrono::ChFunctionPositionSetpoint const &other);
    virtual ~SwigDirector_ChFunctionPositionSetpoint();
    virtual chrono::ChFunctionPositionSetpoint *Clone() const;
    virtual chrono::ChVector3d GetPos(double s) const;
    virtual chrono::ChVector3d GetLinVel(double s) const;
    virtual chrono::ChVector3d GetLinAcc(double s) const;
    virtual void Update(double t);
    virtual void ArchiveOut(chrono::ChArchiveOut &archive_out);
    virtual void ArchiveIn(chrono::ChArchiveIn &archive_in);
    virtual void SetSetpoint(chrono::ChVector3d p_setpoint, double s);
    virtual void SetSetpointAndDerivatives(chrono::ChVector3d p_setpoint, chrono::ChVector3d p_setpoint_ds, chrono::ChVector3d p_setpoint_dsds);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackGetPos, SWIG_Callback1_t callbackGetLinVel, SWIG_Callback2_t callbackGetLinAcc, SWIG_Callback3_t callbackUpdate, SWIG_Callback4_t callbackArchiveOut, SWIG_Callback5_t callbackArchiveIn, SWIG_Callback6_t callbackSetSetpoint, SWIG_Callback7_t callbackSetSetpointAndDerivatives);

private:
    SWIG_Callback0_t swig_callbackGetPos;
    SWIG_Callback1_t swig_callbackGetLinVel;
    SWIG_Callback2_t swig_callbackGetLinAcc;
    SWIG_Callback3_t swig_callbackUpdate;
    SWIG_Callback4_t swig_callbackArchiveOut;
    SWIG_Callback5_t swig_callbackArchiveIn;
    SWIG_Callback6_t swig_callbackSetSetpoint;
    SWIG_Callback7_t swig_callbackSetSetpointAndDerivatives;
    void swig_init_callbacks();
};

class SwigDirector_ChFunctionRotation : public chrono::ChFunctionRotation, public Swig::Director {

public:
    SwigDirector_ChFunctionRotation();
    SwigDirector_ChFunctionRotation(chrono::ChFunctionRotation const &other);
    virtual ~SwigDirector_ChFunctionRotation();
    virtual chrono::ChFunctionRotation *Clone() const;
    virtual chrono::ChQuaternion< > GetQuat(double s) const;
    virtual chrono::ChVector3d GetAngVel(double s) const;
    virtual chrono::ChVector3d GetAngAcc(double s) const;
    virtual void Update(double t);
    virtual void ArchiveOut(chrono::ChArchiveOut &archive_out);
    virtual void ArchiveIn(chrono::ChArchiveIn &archive_in);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackGetQuat, SWIG_Callback1_t callbackGetAngVel, SWIG_Callback2_t callbackGetAngAcc, SWIG_Callback3_t callbackUpdate, SWIG_Callback4_t callbackArchiveOut, SWIG_Callback5_t callbackArchiveIn);

private:
    SWIG_Callback0_t swig_callbackGetQuat;
    SWIG_Callback1_t swig_callbackGetAngVel;
    SWIG_Callback2_t swig_callbackGetAngAcc;
    SWIG_Callback3_t swig_callbackUpdate;
    SWIG_Callback4_t swig_callbackArchiveOut;
    SWIG_Callback5_t swig_callbackArchiveIn;
    void swig_init_callbacks();
};

class SwigDirector_ChFunctionRotationSetpoint : public chrono::ChFunctionRotationSetpoint, public Swig::Director {

public:
    SwigDirector_ChFunctionRotationSetpoint();
    SwigDirector_ChFunctionRotationSetpoint(chrono::ChFunctionRotationSetpoint const &other);
    virtual ~SwigDirector_ChFunctionRotationSetpoint();
    virtual chrono::ChFunctionRotationSetpoint *Clone() const;
    virtual chrono::ChQuaternion< > GetQuat(double s) const;
    virtual chrono::ChVector3d GetAngVel(double s) const;
    virtual chrono::ChVector3d GetAngAcc(double s) const;
    virtual void Update(double t);
    virtual void ArchiveOut(chrono::ChArchiveOut &archive_out);
    virtual void ArchiveIn(chrono::ChArchiveIn &archive_in);
    virtual void SetSetpoint(chrono::ChQuaternion< > q_setpoint, double s);
    virtual void SetSetpointAndDerivatives(chrono::ChQuaternion< > q_setpoint, chrono::ChVector3d w_loc_setpoint, chrono::ChVector3d a_loc_setpoint);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackGetQuat, SWIG_Callback1_t callbackGetAngVel, SWIG_Callback2_t callbackGetAngAcc, SWIG_Callback3_t callbackUpdate, SWIG_Callback4_t callbackArchiveOut, SWIG_Callback5_t callbackArchiveIn, SWIG_Callback6_t callbackSetSetpoint, SWIG_Callback7_t callbackSetSetpointAndDerivatives);

private:
    SWIG_Callback0_t swig_callbackGetQuat;
    SWIG_Callback1_t swig_callbackGetAngVel;
    SWIG_Callback2_t swig_callbackGetAngAcc;
    SWIG_Callback3_t swig_callbackUpdate;
    SWIG_Callback4_t swig_callbackArchiveOut;
    SWIG_Callback5_t swig_callbackArchiveIn;
    SWIG_Callback6_t swig_callbackSetSetpoint;
    SWIG_Callback7_t swig_callbackSetSetpointAndDerivatives;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadable : public chrono::ChLoadable, public Swig::Director {

public:
    SwigDirector_ChLoadable();
    virtual ~SwigDirector_ChLoadable();
    virtual unsigned int GetLoadableNumCoordsPosLevel();
    virtual unsigned int GetLoadableNumCoordsVelLevel();
    virtual void LoadableGetStateBlockPosLevel(int block_offset, chrono::ChState &mD);
    virtual void LoadableGetStateBlockVelLevel(int block_offset, chrono::ChStateDelta &mD);
    virtual void LoadableStateIncrement(unsigned int const off_x, chrono::ChState &x_new, chrono::ChState const &x, unsigned int const off_v, chrono::ChStateDelta const &Dv);
    virtual unsigned int GetNumFieldCoords();
    virtual unsigned int GetNumSubBlocks();
    virtual unsigned int GetSubBlockOffset(unsigned int nblock);
    virtual unsigned int GetSubBlockSize(unsigned int nblock);
    virtual bool IsSubBlockActive(unsigned int nblock) const;
    virtual void LoadableGetVariables(std::vector< ChVariables * > &mvars);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(unsigned int, void *, void *, unsigned int, void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback5_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback7_t)(unsigned int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback8_t)(unsigned int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback9_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackGetLoadableNumCoordsPosLevel, SWIG_Callback1_t callbackGetLoadableNumCoordsVelLevel, SWIG_Callback2_t callbackLoadableGetStateBlockPosLevel, SWIG_Callback3_t callbackLoadableGetStateBlockVelLevel, SWIG_Callback4_t callbackLoadableStateIncrement, SWIG_Callback5_t callbackGetNumFieldCoords, SWIG_Callback6_t callbackGetNumSubBlocks, SWIG_Callback7_t callbackGetSubBlockOffset, SWIG_Callback8_t callbackGetSubBlockSize, SWIG_Callback9_t callbackIsSubBlockActive, SWIG_Callback10_t callbackLoadableGetVariables);

private:
    SWIG_Callback0_t swig_callbackGetLoadableNumCoordsPosLevel;
    SWIG_Callback1_t swig_callbackGetLoadableNumCoordsVelLevel;
    SWIG_Callback2_t swig_callbackLoadableGetStateBlockPosLevel;
    SWIG_Callback3_t swig_callbackLoadableGetStateBlockVelLevel;
    SWIG_Callback4_t swig_callbackLoadableStateIncrement;
    SWIG_Callback5_t swig_callbackGetNumFieldCoords;
    SWIG_Callback6_t swig_callbackGetNumSubBlocks;
    SWIG_Callback7_t swig_callbackGetSubBlockOffset;
    SWIG_Callback8_t swig_callbackGetSubBlockSize;
    SWIG_Callback9_t swig_callbackIsSubBlockActive;
    SWIG_Callback10_t swig_callbackLoadableGetVariables;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadableUVW : public chrono::ChLoadableUVW, public Swig::Director {

public:
    SwigDirector_ChLoadableUVW();
    virtual ~SwigDirector_ChLoadableUVW();
    virtual unsigned int GetLoadableNumCoordsPosLevel();
    virtual unsigned int GetLoadableNumCoordsVelLevel();
    virtual void LoadableGetStateBlockPosLevel(int block_offset, chrono::ChState &mD);
    virtual void LoadableGetStateBlockVelLevel(int block_offset, chrono::ChStateDelta &mD);
    virtual void LoadableStateIncrement(unsigned int const off_x, chrono::ChState &x_new, chrono::ChState const &x, unsigned int const off_v, chrono::ChStateDelta const &Dv);
    virtual unsigned int GetNumFieldCoords();
    virtual unsigned int GetNumSubBlocks();
    virtual unsigned int GetSubBlockOffset(unsigned int nblock);
    virtual unsigned int GetSubBlockSize(unsigned int nblock);
    virtual bool IsSubBlockActive(unsigned int nblock) const;
    virtual void LoadableGetVariables(std::vector< ChVariables * > &mvars);
    virtual void ComputeNF(double const U, double const V, double const W, chrono::ChVectorDynamic< > &Qi, double &detJ, chrono::ChVectorDynamic< > const &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual double GetDensity();
    virtual bool IsTetrahedronIntegrationNeeded();
    virtual bool IsTrianglePrismIntegrationNeeded();

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(unsigned int, void *, void *, unsigned int, void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback5_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback7_t)(unsigned int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback8_t)(unsigned int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback9_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double, double, double, void *, void *, void *, void *, void *);
    typedef double (SWIGSTDCALL* SWIG_Callback12_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback13_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback14_t)();
    void swig_connect_director(SWIG_Callback0_t callbackGetLoadableNumCoordsPosLevel, SWIG_Callback1_t callbackGetLoadableNumCoordsVelLevel, SWIG_Callback2_t callbackLoadableGetStateBlockPosLevel, SWIG_Callback3_t callbackLoadableGetStateBlockVelLevel, SWIG_Callback4_t callbackLoadableStateIncrement, SWIG_Callback5_t callbackGetNumFieldCoords, SWIG_Callback6_t callbackGetNumSubBlocks, SWIG_Callback7_t callbackGetSubBlockOffset, SWIG_Callback8_t callbackGetSubBlockSize, SWIG_Callback9_t callbackIsSubBlockActive, SWIG_Callback10_t callbackLoadableGetVariables, SWIG_Callback11_t callbackComputeNF, SWIG_Callback12_t callbackGetDensity, SWIG_Callback13_t callbackIsTetrahedronIntegrationNeeded, SWIG_Callback14_t callbackIsTrianglePrismIntegrationNeeded);

private:
    SWIG_Callback0_t swig_callbackGetLoadableNumCoordsPosLevel;
    SWIG_Callback1_t swig_callbackGetLoadableNumCoordsVelLevel;
    SWIG_Callback2_t swig_callbackLoadableGetStateBlockPosLevel;
    SWIG_Callback3_t swig_callbackLoadableGetStateBlockVelLevel;
    SWIG_Callback4_t swig_callbackLoadableStateIncrement;
    SWIG_Callback5_t swig_callbackGetNumFieldCoords;
    SWIG_Callback6_t swig_callbackGetNumSubBlocks;
    SWIG_Callback7_t swig_callbackGetSubBlockOffset;
    SWIG_Callback8_t swig_callbackGetSubBlockSize;
    SWIG_Callback9_t swig_callbackIsSubBlockActive;
    SWIG_Callback10_t swig_callbackLoadableGetVariables;
    SWIG_Callback11_t swig_callbackComputeNF;
    SWIG_Callback12_t swig_callbackGetDensity;
    SWIG_Callback13_t swig_callbackIsTetrahedronIntegrationNeeded;
    SWIG_Callback14_t swig_callbackIsTrianglePrismIntegrationNeeded;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadableUV : public chrono::ChLoadableUV, public Swig::Director {

public:
    SwigDirector_ChLoadableUV();
    virtual ~SwigDirector_ChLoadableUV();
    virtual unsigned int GetLoadableNumCoordsPosLevel();
    virtual unsigned int GetLoadableNumCoordsVelLevel();
    virtual void LoadableGetStateBlockPosLevel(int block_offset, chrono::ChState &mD);
    virtual void LoadableGetStateBlockVelLevel(int block_offset, chrono::ChStateDelta &mD);
    virtual void LoadableStateIncrement(unsigned int const off_x, chrono::ChState &x_new, chrono::ChState const &x, unsigned int const off_v, chrono::ChStateDelta const &Dv);
    virtual unsigned int GetNumFieldCoords();
    virtual unsigned int GetNumSubBlocks();
    virtual unsigned int GetSubBlockOffset(unsigned int nblock);
    virtual unsigned int GetSubBlockSize(unsigned int nblock);
    virtual bool IsSubBlockActive(unsigned int nblock) const;
    virtual void LoadableGetVariables(std::vector< ChVariables * > &mvars);
    virtual void ComputeNF(double const U, double const V, chrono::ChVectorDynamic< > &Qi, double &detJ, chrono::ChVectorDynamic< > const &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual chrono::ChVector3d ComputeNormal(double const U, double const V);
    virtual bool IsTriangleIntegrationNeeded();

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(unsigned int, void *, void *, unsigned int, void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback5_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback7_t)(unsigned int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback8_t)(unsigned int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback9_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double, double, void *, void *, void *, void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback12_t)(double, double);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback13_t)();
    void swig_connect_director(SWIG_Callback0_t callbackGetLoadableNumCoordsPosLevel, SWIG_Callback1_t callbackGetLoadableNumCoordsVelLevel, SWIG_Callback2_t callbackLoadableGetStateBlockPosLevel, SWIG_Callback3_t callbackLoadableGetStateBlockVelLevel, SWIG_Callback4_t callbackLoadableStateIncrement, SWIG_Callback5_t callbackGetNumFieldCoords, SWIG_Callback6_t callbackGetNumSubBlocks, SWIG_Callback7_t callbackGetSubBlockOffset, SWIG_Callback8_t callbackGetSubBlockSize, SWIG_Callback9_t callbackIsSubBlockActive, SWIG_Callback10_t callbackLoadableGetVariables, SWIG_Callback11_t callbackComputeNF, SWIG_Callback12_t callbackComputeNormal, SWIG_Callback13_t callbackIsTriangleIntegrationNeeded);

private:
    SWIG_Callback0_t swig_callbackGetLoadableNumCoordsPosLevel;
    SWIG_Callback1_t swig_callbackGetLoadableNumCoordsVelLevel;
    SWIG_Callback2_t swig_callbackLoadableGetStateBlockPosLevel;
    SWIG_Callback3_t swig_callbackLoadableGetStateBlockVelLevel;
    SWIG_Callback4_t swig_callbackLoadableStateIncrement;
    SWIG_Callback5_t swig_callbackGetNumFieldCoords;
    SWIG_Callback6_t swig_callbackGetNumSubBlocks;
    SWIG_Callback7_t swig_callbackGetSubBlockOffset;
    SWIG_Callback8_t swig_callbackGetSubBlockSize;
    SWIG_Callback9_t swig_callbackIsSubBlockActive;
    SWIG_Callback10_t swig_callbackLoadableGetVariables;
    SWIG_Callback11_t swig_callbackComputeNF;
    SWIG_Callback12_t swig_callbackComputeNormal;
    SWIG_Callback13_t swig_callbackIsTriangleIntegrationNeeded;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadableU : public chrono::ChLoadableU, public Swig::Director {

public:
    SwigDirector_ChLoadableU();
    virtual ~SwigDirector_ChLoadableU();
    virtual unsigned int GetLoadableNumCoordsPosLevel();
    virtual unsigned int GetLoadableNumCoordsVelLevel();
    virtual void LoadableGetStateBlockPosLevel(int block_offset, chrono::ChState &mD);
    virtual void LoadableGetStateBlockVelLevel(int block_offset, chrono::ChStateDelta &mD);
    virtual void LoadableStateIncrement(unsigned int const off_x, chrono::ChState &x_new, chrono::ChState const &x, unsigned int const off_v, chrono::ChStateDelta const &Dv);
    virtual unsigned int GetNumFieldCoords();
    virtual unsigned int GetNumSubBlocks();
    virtual unsigned int GetSubBlockOffset(unsigned int nblock);
    virtual unsigned int GetSubBlockSize(unsigned int nblock);
    virtual bool IsSubBlockActive(unsigned int nblock) const;
    virtual void LoadableGetVariables(std::vector< ChVariables * > &mvars);
    virtual void ComputeNF(double const U, chrono::ChVectorDynamic< > &Qi, double &detJ, chrono::ChVectorDynamic< > const &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(unsigned int, void *, void *, unsigned int, void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback5_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback7_t)(unsigned int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback8_t)(unsigned int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback9_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double, void *, void *, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackGetLoadableNumCoordsPosLevel, SWIG_Callback1_t callbackGetLoadableNumCoordsVelLevel, SWIG_Callback2_t callbackLoadableGetStateBlockPosLevel, SWIG_Callback3_t callbackLoadableGetStateBlockVelLevel, SWIG_Callback4_t callbackLoadableStateIncrement, SWIG_Callback5_t callbackGetNumFieldCoords, SWIG_Callback6_t callbackGetNumSubBlocks, SWIG_Callback7_t callbackGetSubBlockOffset, SWIG_Callback8_t callbackGetSubBlockSize, SWIG_Callback9_t callbackIsSubBlockActive, SWIG_Callback10_t callbackLoadableGetVariables, SWIG_Callback11_t callbackComputeNF);

private:
    SWIG_Callback0_t swig_callbackGetLoadableNumCoordsPosLevel;
    SWIG_Callback1_t swig_callbackGetLoadableNumCoordsVelLevel;
    SWIG_Callback2_t swig_callbackLoadableGetStateBlockPosLevel;
    SWIG_Callback3_t swig_callbackLoadableGetStateBlockVelLevel;
    SWIG_Callback4_t swig_callbackLoadableStateIncrement;
    SWIG_Callback5_t swig_callbackGetNumFieldCoords;
    SWIG_Callback6_t swig_callbackGetNumSubBlocks;
    SWIG_Callback7_t swig_callbackGetSubBlockOffset;
    SWIG_Callback8_t swig_callbackGetSubBlockSize;
    SWIG_Callback9_t swig_callbackIsSubBlockActive;
    SWIG_Callback10_t swig_callbackLoadableGetVariables;
    SWIG_Callback11_t swig_callbackComputeNF;
    void swig_init_callbacks();
};

class SwigDirector_TSDAForceFunctor : public TSDAForceFunctor, public Swig::Director {

public:
    SwigDirector_TSDAForceFunctor();
    virtual ~SwigDirector_TSDAForceFunctor();
    virtual double evaluate(double time, double rest_length, double length, double vel, chrono::ChLinkTSDA const &link);

    typedef double (SWIGSTDCALL* SWIG_Callback0_t)(double, double, double, double, void *);
    void swig_connect_director(SWIG_Callback0_t callbackevaluate);

private:
    SWIG_Callback0_t swig_callbackevaluate;
    void swig_init_callbacks();
};

class SwigDirector_RSDATorqueFunctor : public RSDATorqueFunctor, public Swig::Director {

public:
    SwigDirector_RSDATorqueFunctor();
    virtual ~SwigDirector_RSDATorqueFunctor();
    virtual double evaluate(double time, double rest_angle, double angle, double vel, chrono::ChLinkRSDA const &link);

    typedef double (SWIGSTDCALL* SWIG_Callback0_t)(double, double, double, double, void *);
    void swig_connect_director(SWIG_Callback0_t callbackevaluate);

private:
    SWIG_Callback0_t swig_callbackevaluate;
    void swig_init_callbacks();
};

class SwigDirector_AddContactCallback : public chrono::ChContactContainer::AddContactCallback, public Swig::Director {

public:
    SwigDirector_AddContactCallback();
    virtual ~SwigDirector_AddContactCallback();
    virtual void OnAddContact(chrono::ChCollisionInfo const &contactinfo, chrono::ChContactMaterialComposite *const material);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnAddContact);

private:
    SWIG_Callback0_t swig_callbackOnAddContact;
    void swig_init_callbacks();
};

class SwigDirector_ReportContactCallback : public chrono::ChContactContainer::ReportContactCallback, public Swig::Director {

public:
    SwigDirector_ReportContactCallback();
    virtual ~SwigDirector_ReportContactCallback();
    virtual bool OnReportContact(chrono::ChVector3d const &pA, chrono::ChVector3d const &pB, chrono::ChMatrix33< > const &plane_coord, double const &distance, double const &eff_radius, chrono::ChVector3d const &react_forces, chrono::ChVector3d const &react_torques, chrono::ChContactable *contactobjA, chrono::ChContactable *contactobjB);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *, double, double, void *, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnReportContact);

private:
    SWIG_Callback0_t swig_callbackOnReportContact;
    void swig_init_callbacks();
};

class SwigDirector_CustomCollisionCallback : public chrono::ChSystem::CustomCollisionCallback, public Swig::Director {

public:
    SwigDirector_CustomCollisionCallback();
    virtual ~SwigDirector_CustomCollisionCallback();
    virtual void OnCustomCollision(chrono::ChSystem *msys);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnCustomCollision);

private:
    SWIG_Callback0_t swig_callbackOnCustomCollision;
    void swig_init_callbacks();
};

class SwigDirector_ChReportProximityCallbackP : public ChReportProximityCallbackP, public Swig::Director {

public:
    SwigDirector_ChReportProximityCallbackP();
    virtual ~SwigDirector_ChReportProximityCallbackP();
    virtual bool OnReportProximity(chrono::ChCollisionModel *modA, chrono::ChCollisionModel *modB);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnReportProximity);

private:
    SWIG_Callback0_t swig_callbackOnReportProximity;
    void swig_init_callbacks();
};

class SwigDirector_ChAddProximityCallbackP : public ChAddProximityCallbackP, public Swig::Director {

public:
    SwigDirector_ChAddProximityCallbackP();
    virtual ~SwigDirector_ChAddProximityCallbackP();
    virtual void OnAddProximity(chrono::ChCollisionModel const &modA, chrono::ChCollisionModel const &modB);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnAddProximity);

private:
    SWIG_Callback0_t swig_callbackOnAddProximity;
    void swig_init_callbacks();
};

class SwigDirector_ChLoader : public chrono::ChLoader, public Swig::Director {

public:
    SwigDirector_ChLoader();
    virtual ~SwigDirector_ChLoader();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderU : public chrono::ChLoaderU, public Swig::Director {

public:
    SwigDirector_ChLoaderU(std::shared_ptr< chrono::ChLoadableU > mloadable);
    virtual ~SwigDirector_ChLoaderU();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderUdistributed : public chrono::ChLoaderUdistributed, public Swig::Director {

public:
    SwigDirector_ChLoaderUdistributed(std::shared_ptr< chrono::ChLoadableU > mloadable);
    virtual ~SwigDirector_ChLoaderUdistributed();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual int GetIntegrationPointsU();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback4_t)();
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF, SWIG_Callback4_t callbackGetIntegrationPointsU);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    SWIG_Callback4_t swig_callbackGetIntegrationPointsU;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderUatomic : public chrono::ChLoaderUatomic, public Swig::Director {

public:
    SwigDirector_ChLoaderUatomic(std::shared_ptr< chrono::ChLoadableU > mloadable);
    virtual ~SwigDirector_ChLoaderUatomic();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderUV : public chrono::ChLoaderUV, public Swig::Director {

public:
    SwigDirector_ChLoaderUV(std::shared_ptr< chrono::ChLoadableUV > mloadable);
    virtual ~SwigDirector_ChLoaderUV();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, double V, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, double, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderUVdistributed : public chrono::ChLoaderUVdistributed, public Swig::Director {

public:
    SwigDirector_ChLoaderUVdistributed(std::shared_ptr< chrono::ChLoadableUV > mloadable);
    virtual ~SwigDirector_ChLoaderUVdistributed();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, double V, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual int GetIntegrationPointsU();
    virtual int GetIntegrationPointsV();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, double, void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback5_t)();
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF, SWIG_Callback4_t callbackGetIntegrationPointsU, SWIG_Callback5_t callbackGetIntegrationPointsV);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    SWIG_Callback4_t swig_callbackGetIntegrationPointsU;
    SWIG_Callback5_t swig_callbackGetIntegrationPointsV;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderUVatomic : public chrono::ChLoaderUVatomic, public Swig::Director {

public:
    SwigDirector_ChLoaderUVatomic(std::shared_ptr< chrono::ChLoadableUV > mloadable);
    virtual ~SwigDirector_ChLoaderUVatomic();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, double V, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, double, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderForceOnSurface : public chrono::ChLoaderForceOnSurface, public Swig::Director {

public:
    SwigDirector_ChLoaderForceOnSurface(std::shared_ptr< chrono::ChLoadableUV > mloadable);
    virtual ~SwigDirector_ChLoaderForceOnSurface();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, double V, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, double, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderPressure : public chrono::ChLoaderPressure, public Swig::Director {

public:
    SwigDirector_ChLoaderPressure(std::shared_ptr< chrono::ChLoadableUV > mloadable);
    virtual ~SwigDirector_ChLoaderPressure();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, double V, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual int GetIntegrationPointsU();
    virtual int GetIntegrationPointsV();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, double, void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback5_t)();
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF, SWIG_Callback4_t callbackGetIntegrationPointsU, SWIG_Callback5_t callbackGetIntegrationPointsV);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    SWIG_Callback4_t swig_callbackGetIntegrationPointsU;
    SWIG_Callback5_t swig_callbackGetIntegrationPointsV;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderUVW : public chrono::ChLoaderUVW, public Swig::Director {

public:
    SwigDirector_ChLoaderUVW(std::shared_ptr< chrono::ChLoadableUVW > mloadable);
    virtual ~SwigDirector_ChLoaderUVW();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, double V, double W, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, double, double, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderUVWdistributed : public chrono::ChLoaderUVWdistributed, public Swig::Director {

public:
    SwigDirector_ChLoaderUVWdistributed(std::shared_ptr< chrono::ChLoadableUVW > mloadable);
    virtual ~SwigDirector_ChLoaderUVWdistributed();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, double V, double W, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual int GetIntegrationPointsU();
    virtual int GetIntegrationPointsV();
    virtual int GetIntegrationPointsW();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, double, double, void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback5_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback6_t)();
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF, SWIG_Callback4_t callbackGetIntegrationPointsU, SWIG_Callback5_t callbackGetIntegrationPointsV, SWIG_Callback6_t callbackGetIntegrationPointsW);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    SWIG_Callback4_t swig_callbackGetIntegrationPointsU;
    SWIG_Callback5_t swig_callbackGetIntegrationPointsV;
    SWIG_Callback6_t swig_callbackGetIntegrationPointsW;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderUVWatomic : public chrono::ChLoaderUVWatomic, public Swig::Director {

public:
    SwigDirector_ChLoaderUVWatomic(std::shared_ptr< chrono::ChLoadableUVW > mloadable, double mU, double mV, double mW);
    virtual ~SwigDirector_ChLoaderUVWatomic();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, double V, double W, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, double, double, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderGravity : public chrono::ChLoaderGravity, public Swig::Director {

public:
    SwigDirector_ChLoaderGravity(std::shared_ptr< chrono::ChLoadableUVW > mloadable);
    virtual ~SwigDirector_ChLoaderGravity();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, double V, double W, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual int GetIntegrationPointsU();
    virtual int GetIntegrationPointsV();
    virtual int GetIntegrationPointsW();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, double, double, void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback5_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback6_t)();
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF, SWIG_Callback4_t callbackGetIntegrationPointsU, SWIG_Callback5_t callbackGetIntegrationPointsV, SWIG_Callback6_t callbackGetIntegrationPointsW);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    SWIG_Callback4_t swig_callbackGetIntegrationPointsU;
    SWIG_Callback5_t swig_callbackGetIntegrationPointsV;
    SWIG_Callback6_t swig_callbackGetIntegrationPointsW;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadBase : public chrono::ChLoadBase, public Swig::Director {

public:
    SwigDirector_ChLoadBase();
    virtual ~SwigDirector_ChLoadBase();
    virtual chrono::ChObj *Clone() const;
    virtual void ArchiveOut(chrono::ChArchiveOut &archive_out);
    virtual void ArchiveIn(chrono::ChArchiveIn &archive_in);
    virtual std::string &ArchiveContainerName();
    virtual int LoadGetNumCoordsPosLevel();
    virtual int LoadGetNumCoordsVelLevel();
    virtual void LoadGetStateBlock_x(chrono::ChState &mD);
    virtual void LoadGetStateBlock_w(chrono::ChStateDelta &mD);
    virtual void LoadStateIncrement(chrono::ChState const &x, chrono::ChStateDelta const &dw, chrono::ChState &x_new);
    virtual int LoadGetNumFieldCoords();
    virtual void ComputeQ(chrono::ChState *state_x, chrono::ChStateDelta *state_w);
    virtual void ComputeJacobian(chrono::ChState *state_x, chrono::ChStateDelta *state_w);
    virtual void CreateJacobianMatrices();
    virtual void Update(double time);
    virtual bool IsStiff();
    virtual void LoadIntLoadResidual_F(chrono::ChVectorDynamic< > &R, double c);
    virtual void LoadIntLoadResidual_Mv(chrono::ChVectorDynamic< > &R, chrono::ChVectorDynamic< > const &w, double c);
    virtual void LoadIntLoadLumpedMass_Md(chrono::ChVectorDynamic< > &Md, double &err, double const c);
    virtual void InjectKRMMatrices(ChSystemDescriptor &descriptor);
    virtual void LoadKRMMatrices(double Kfactor, double Rfactor, double Mfactor);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback7_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(double);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback11_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(void *, void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(void *, void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(double, double, double);
    void swig_connect_director(SWIG_Callback0_t callbackArchiveOut, SWIG_Callback1_t callbackArchiveIn, SWIG_Callback2_t callbackLoadGetNumCoordsPosLevel, SWIG_Callback3_t callbackLoadGetNumCoordsVelLevel, SWIG_Callback4_t callbackLoadGetStateBlock_x, SWIG_Callback5_t callbackLoadGetStateBlock_w, SWIG_Callback6_t callbackLoadStateIncrement, SWIG_Callback7_t callbackLoadGetNumFieldCoords, SWIG_Callback8_t callbackComputeQ, SWIG_Callback9_t callbackCreateJacobianMatrices, SWIG_Callback10_t callbackUpdate, SWIG_Callback11_t callbackIsStiff, SWIG_Callback12_t callbackLoadIntLoadResidual_F, SWIG_Callback13_t callbackLoadIntLoadResidual_Mv, SWIG_Callback14_t callbackLoadIntLoadLumpedMass_Md, SWIG_Callback15_t callbackInjectKRMMatrices, SWIG_Callback16_t callbackLoadKRMMatrices);

private:
    SWIG_Callback0_t swig_callbackArchiveOut;
    SWIG_Callback1_t swig_callbackArchiveIn;
    SWIG_Callback2_t swig_callbackLoadGetNumCoordsPosLevel;
    SWIG_Callback3_t swig_callbackLoadGetNumCoordsVelLevel;
    SWIG_Callback4_t swig_callbackLoadGetStateBlock_x;
    SWIG_Callback5_t swig_callbackLoadGetStateBlock_w;
    SWIG_Callback6_t swig_callbackLoadStateIncrement;
    SWIG_Callback7_t swig_callbackLoadGetNumFieldCoords;
    SWIG_Callback8_t swig_callbackComputeQ;
    SWIG_Callback9_t swig_callbackCreateJacobianMatrices;
    SWIG_Callback10_t swig_callbackUpdate;
    SWIG_Callback11_t swig_callbackIsStiff;
    SWIG_Callback12_t swig_callbackLoadIntLoadResidual_F;
    SWIG_Callback13_t swig_callbackLoadIntLoadResidual_Mv;
    SWIG_Callback14_t swig_callbackLoadIntLoadLumpedMass_Md;
    SWIG_Callback15_t swig_callbackInjectKRMMatrices;
    SWIG_Callback16_t swig_callbackLoadKRMMatrices;
    void swig_init_callbacks();
};

class SwigDirector_ChLoad : public chrono::ChLoad, public Swig::Director {

public:
    SwigDirector_ChLoad();
    SwigDirector_ChLoad(std::shared_ptr< chrono::ChLoader > loader_object);
    virtual ~SwigDirector_ChLoad();
    virtual chrono::ChLoad *Clone() const;
    virtual void ArchiveOut(chrono::ChArchiveOut &archive_out);
    virtual void ArchiveIn(chrono::ChArchiveIn &archive_in);
    virtual std::string &ArchiveContainerName();
    virtual int LoadGetNumCoordsPosLevel();
    virtual int LoadGetNumCoordsVelLevel();
    virtual void LoadGetStateBlock_x(chrono::ChState &mD);
    virtual void LoadGetStateBlock_w(chrono::ChStateDelta &mD);
    virtual void LoadStateIncrement(chrono::ChState const &x, chrono::ChStateDelta const &dw, chrono::ChState &x_new);
    virtual int LoadGetNumFieldCoords();
    virtual void ComputeQ(chrono::ChState *state_x, chrono::ChStateDelta *state_w);
    virtual void ComputeJacobian(chrono::ChState *state_x, chrono::ChStateDelta *state_w);
    virtual void CreateJacobianMatrices();
    virtual void Update(double time);
    virtual bool IsStiff();
    virtual void LoadIntLoadResidual_F(chrono::ChVectorDynamic< > &R, double c);
    virtual void LoadIntLoadResidual_Mv(chrono::ChVectorDynamic< > &R, chrono::ChVectorDynamic< > const &w, double c);
    virtual void LoadIntLoadLumpedMass_Md(chrono::ChVectorDynamic< > &Md, double &err, double const c);
    virtual void InjectKRMMatrices(ChSystemDescriptor &descriptor);
    virtual void LoadKRMMatrices(double Kfactor, double Rfactor, double Mfactor);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback7_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(double);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback11_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(void *, void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(void *, void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(double, double, double);
    void swig_connect_director(SWIG_Callback0_t callbackArchiveOut, SWIG_Callback1_t callbackArchiveIn, SWIG_Callback2_t callbackLoadGetNumCoordsPosLevel, SWIG_Callback3_t callbackLoadGetNumCoordsVelLevel, SWIG_Callback4_t callbackLoadGetStateBlock_x, SWIG_Callback5_t callbackLoadGetStateBlock_w, SWIG_Callback6_t callbackLoadStateIncrement, SWIG_Callback7_t callbackLoadGetNumFieldCoords, SWIG_Callback8_t callbackComputeQ, SWIG_Callback9_t callbackCreateJacobianMatrices, SWIG_Callback10_t callbackUpdate, SWIG_Callback11_t callbackIsStiff, SWIG_Callback12_t callbackLoadIntLoadResidual_F, SWIG_Callback13_t callbackLoadIntLoadResidual_Mv, SWIG_Callback14_t callbackLoadIntLoadLumpedMass_Md, SWIG_Callback15_t callbackInjectKRMMatrices, SWIG_Callback16_t callbackLoadKRMMatrices);

private:
    SWIG_Callback0_t swig_callbackArchiveOut;
    SWIG_Callback1_t swig_callbackArchiveIn;
    SWIG_Callback2_t swig_callbackLoadGetNumCoordsPosLevel;
    SWIG_Callback3_t swig_callbackLoadGetNumCoordsVelLevel;
    SWIG_Callback4_t swig_callbackLoadGetStateBlock_x;
    SWIG_Callback5_t swig_callbackLoadGetStateBlock_w;
    SWIG_Callback6_t swig_callbackLoadStateIncrement;
    SWIG_Callback7_t swig_callbackLoadGetNumFieldCoords;
    SWIG_Callback8_t swig_callbackComputeQ;
    SWIG_Callback9_t swig_callbackCreateJacobianMatrices;
    SWIG_Callback10_t swig_callbackUpdate;
    SWIG_Callback11_t swig_callbackIsStiff;
    SWIG_Callback12_t swig_callbackLoadIntLoadResidual_F;
    SWIG_Callback13_t swig_callbackLoadIntLoadResidual_Mv;
    SWIG_Callback14_t swig_callbackLoadIntLoadLumpedMass_Md;
    SWIG_Callback15_t swig_callbackInjectKRMMatrices;
    SWIG_Callback16_t swig_callbackLoadKRMMatrices;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadCustom : public chrono::ChLoadCustom, public Swig::Director {

public:
    SwigDirector_ChLoadCustom(std::shared_ptr< chrono::ChLoadable > loadable_object);
    virtual ~SwigDirector_ChLoadCustom();
    virtual chrono::ChObj *Clone() const;
    virtual void ArchiveOut(chrono::ChArchiveOut &archive_out);
    virtual void ArchiveIn(chrono::ChArchiveIn &archive_in);
    virtual std::string &ArchiveContainerName();
    virtual int LoadGetNumCoordsPosLevel();
    virtual int LoadGetNumCoordsVelLevel();
    virtual void LoadGetStateBlock_x(chrono::ChState &mD);
    virtual void LoadGetStateBlock_w(chrono::ChStateDelta &mD);
    virtual void LoadStateIncrement(chrono::ChState const &x, chrono::ChStateDelta const &dw, chrono::ChState &x_new);
    virtual int LoadGetNumFieldCoords();
    virtual void ComputeQ(chrono::ChState *state_x, chrono::ChStateDelta *state_w);
    virtual void ComputeJacobian(chrono::ChState *state_x, chrono::ChStateDelta *state_w);
    virtual void CreateJacobianMatrices();
    virtual void Update(double time);
    virtual bool IsStiff();
    virtual void LoadIntLoadResidual_F(chrono::ChVectorDynamic< > &R, double c);
    virtual void LoadIntLoadResidual_Mv(chrono::ChVectorDynamic< > &R, chrono::ChVectorDynamic< > const &w, double c);
    virtual void LoadIntLoadLumpedMass_Md(chrono::ChVectorDynamic< > &Md, double &err, double const c);
    virtual void InjectKRMMatrices(ChSystemDescriptor &descriptor);
    virtual void LoadKRMMatrices(double Kfactor, double Rfactor, double Mfactor);
    virtual chrono::ChVectorDynamic< > &GetQ();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback7_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(double);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback11_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(void *, void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(void *, void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(double, double, double);
    typedef void * (SWIGSTDCALL* SWIG_Callback17_t)();
    void swig_connect_director(SWIG_Callback0_t callbackArchiveOut, SWIG_Callback1_t callbackArchiveIn, SWIG_Callback2_t callbackLoadGetNumCoordsPosLevel, SWIG_Callback3_t callbackLoadGetNumCoordsVelLevel, SWIG_Callback4_t callbackLoadGetStateBlock_x, SWIG_Callback5_t callbackLoadGetStateBlock_w, SWIG_Callback6_t callbackLoadStateIncrement, SWIG_Callback7_t callbackLoadGetNumFieldCoords, SWIG_Callback8_t callbackComputeQ, SWIG_Callback9_t callbackCreateJacobianMatrices, SWIG_Callback10_t callbackUpdate, SWIG_Callback11_t callbackIsStiff, SWIG_Callback12_t callbackLoadIntLoadResidual_F, SWIG_Callback13_t callbackLoadIntLoadResidual_Mv, SWIG_Callback14_t callbackLoadIntLoadLumpedMass_Md, SWIG_Callback15_t callbackInjectKRMMatrices, SWIG_Callback16_t callbackLoadKRMMatrices, SWIG_Callback17_t callbackGetQ);

private:
    SWIG_Callback0_t swig_callbackArchiveOut;
    SWIG_Callback1_t swig_callbackArchiveIn;
    SWIG_Callback2_t swig_callbackLoadGetNumCoordsPosLevel;
    SWIG_Callback3_t swig_callbackLoadGetNumCoordsVelLevel;
    SWIG_Callback4_t swig_callbackLoadGetStateBlock_x;
    SWIG_Callback5_t swig_callbackLoadGetStateBlock_w;
    SWIG_Callback6_t swig_callbackLoadStateIncrement;
    SWIG_Callback7_t swig_callbackLoadGetNumFieldCoords;
    SWIG_Callback8_t swig_callbackComputeQ;
    SWIG_Callback9_t swig_callbackCreateJacobianMatrices;
    SWIG_Callback10_t swig_callbackUpdate;
    SWIG_Callback11_t swig_callbackIsStiff;
    SWIG_Callback12_t swig_callbackLoadIntLoadResidual_F;
    SWIG_Callback13_t swig_callbackLoadIntLoadResidual_Mv;
    SWIG_Callback14_t swig_callbackLoadIntLoadLumpedMass_Md;
    SWIG_Callback15_t swig_callbackInjectKRMMatrices;
    SWIG_Callback16_t swig_callbackLoadKRMMatrices;
    SWIG_Callback17_t swig_callbackGetQ;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadCustomMultiple : public chrono::ChLoadCustomMultiple, public Swig::Director {

public:
    SwigDirector_ChLoadCustomMultiple(std::vector< std::shared_ptr< chrono::ChLoadable > > &loadable_objects);
    SwigDirector_ChLoadCustomMultiple(std::shared_ptr< chrono::ChLoadable > loadableA, std::shared_ptr< chrono::ChLoadable > loadableB);
    SwigDirector_ChLoadCustomMultiple(std::shared_ptr< chrono::ChLoadable > loadableA, std::shared_ptr< chrono::ChLoadable > loadableB, std::shared_ptr< chrono::ChLoadable > loadableC);
    virtual ~SwigDirector_ChLoadCustomMultiple();
    virtual chrono::ChObj *Clone() const;
    virtual void ArchiveOut(chrono::ChArchiveOut &archive_out);
    virtual void ArchiveIn(chrono::ChArchiveIn &archive_in);
    virtual std::string &ArchiveContainerName();
    virtual int LoadGetNumCoordsPosLevel();
    virtual int LoadGetNumCoordsVelLevel();
    virtual void LoadGetStateBlock_x(chrono::ChState &mD);
    virtual void LoadGetStateBlock_w(chrono::ChStateDelta &mD);
    virtual void LoadStateIncrement(chrono::ChState const &x, chrono::ChStateDelta const &dw, chrono::ChState &x_new);
    virtual int LoadGetNumFieldCoords();
    virtual void ComputeQ(chrono::ChState *state_x, chrono::ChStateDelta *state_w);
    virtual void ComputeJacobian(chrono::ChState *state_x, chrono::ChStateDelta *state_w);
    virtual void CreateJacobianMatrices();
    virtual void Update(double time);
    virtual bool IsStiff();
    virtual void LoadIntLoadResidual_F(chrono::ChVectorDynamic< > &R, double c);
    virtual void LoadIntLoadResidual_Mv(chrono::ChVectorDynamic< > &R, chrono::ChVectorDynamic< > const &w, double c);
    virtual void LoadIntLoadLumpedMass_Md(chrono::ChVectorDynamic< > &Md, double &err, double const c);
    virtual void InjectKRMMatrices(ChSystemDescriptor &descriptor);
    virtual void LoadKRMMatrices(double Kfactor, double Rfactor, double Mfactor);
    virtual chrono::ChVectorDynamic< > &GetQ();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback7_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(double);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback11_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(void *, void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(void *, void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(double, double, double);
    typedef void * (SWIGSTDCALL* SWIG_Callback17_t)();
    void swig_connect_director(SWIG_Callback0_t callbackArchiveOut, SWIG_Callback1_t callbackArchiveIn, SWIG_Callback2_t callbackLoadGetNumCoordsPosLevel, SWIG_Callback3_t callbackLoadGetNumCoordsVelLevel, SWIG_Callback4_t callbackLoadGetStateBlock_x, SWIG_Callback5_t callbackLoadGetStateBlock_w, SWIG_Callback6_t callbackLoadStateIncrement, SWIG_Callback7_t callbackLoadGetNumFieldCoords, SWIG_Callback8_t callbackComputeQ, SWIG_Callback9_t callbackCreateJacobianMatrices, SWIG_Callback10_t callbackUpdate, SWIG_Callback11_t callbackIsStiff, SWIG_Callback12_t callbackLoadIntLoadResidual_F, SWIG_Callback13_t callbackLoadIntLoadResidual_Mv, SWIG_Callback14_t callbackLoadIntLoadLumpedMass_Md, SWIG_Callback15_t callbackInjectKRMMatrices, SWIG_Callback16_t callbackLoadKRMMatrices, SWIG_Callback17_t callbackGetQ);

private:
    SWIG_Callback0_t swig_callbackArchiveOut;
    SWIG_Callback1_t swig_callbackArchiveIn;
    SWIG_Callback2_t swig_callbackLoadGetNumCoordsPosLevel;
    SWIG_Callback3_t swig_callbackLoadGetNumCoordsVelLevel;
    SWIG_Callback4_t swig_callbackLoadGetStateBlock_x;
    SWIG_Callback5_t swig_callbackLoadGetStateBlock_w;
    SWIG_Callback6_t swig_callbackLoadStateIncrement;
    SWIG_Callback7_t swig_callbackLoadGetNumFieldCoords;
    SWIG_Callback8_t swig_callbackComputeQ;
    SWIG_Callback9_t swig_callbackCreateJacobianMatrices;
    SWIG_Callback10_t swig_callbackUpdate;
    SWIG_Callback11_t swig_callbackIsStiff;
    SWIG_Callback12_t swig_callbackLoadIntLoadResidual_F;
    SWIG_Callback13_t swig_callbackLoadIntLoadResidual_Mv;
    SWIG_Callback14_t swig_callbackLoadIntLoadLumpedMass_Md;
    SWIG_Callback15_t swig_callbackInjectKRMMatrices;
    SWIG_Callback16_t swig_callbackLoadKRMMatrices;
    SWIG_Callback17_t swig_callbackGetQ;
    void swig_init_callbacks();
};

class SwigDirector_ChLoaderNodeXYZ : public chrono::ChLoaderNodeXYZ, public Swig::Director {

public:
    SwigDirector_ChLoaderNodeXYZ(std::shared_ptr< chrono::ChLoadableUVW > loadable);
    virtual ~SwigDirector_ChLoaderNodeXYZ();
    virtual void ComputeQ(chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual std::shared_ptr< chrono::ChLoadable > GetLoadable();
    virtual bool IsStiff();
    virtual void ComputeF(double U, double V, double W, chrono::ChVectorDynamic< > &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(double, double, double, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackComputeQ, SWIG_Callback1_t callbackGetLoadable, SWIG_Callback2_t callbackIsStiff, SWIG_Callback3_t callbackComputeF);

private:
    SWIG_Callback0_t swig_callbackComputeQ;
    SWIG_Callback1_t swig_callbackGetLoadable;
    SWIG_Callback2_t swig_callbackIsStiff;
    SWIG_Callback3_t swig_callbackComputeF;
    void swig_init_callbacks();
};

class SwigDirector_ChRandomShapeCreator_AddBodyCallback : public chrono::particlefactory::ChRandomShapeCreator::AddBodyCallback, public Swig::Director {

public:
    SwigDirector_ChRandomShapeCreator_AddBodyCallback();
    virtual ~SwigDirector_ChRandomShapeCreator_AddBodyCallback();
    virtual void OnAddBody(std::shared_ptr< chrono::ChBody > mbody, chrono::ChCoordsys< > mcoords, chrono::particlefactory::ChRandomShapeCreator &mcreator);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnAddBody);

private:
    SWIG_Callback0_t swig_callbackOnAddBody;
    void swig_init_callbacks();
};


#endif
