//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ChParticleEventFlowInRectangle : ChParticleEventTrigger {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal ChParticleEventFlowInRectangle(global::System.IntPtr cPtr, bool cMemoryOwn) : base(chronoPINVOKE.ChParticleEventFlowInRectangle_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChParticleEventFlowInRectangle obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          chronoPINVOKE.delete_ChParticleEventFlowInRectangle(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ChParticleEventFlowInRectangle(double mXsize, double mYsize) : this(chronoPINVOKE.new_ChParticleEventFlowInRectangle__SWIG_0(mXsize, mYsize), true) {
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  public ChParticleEventFlowInRectangle(double mXsize) : this(chronoPINVOKE.new_ChParticleEventFlowInRectangle__SWIG_1(mXsize), true) {
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  public ChParticleEventFlowInRectangle() : this(chronoPINVOKE.new_ChParticleEventFlowInRectangle__SWIG_2(), true) {
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool TriggerEvent(ChBody mbody, ChSystem msystem) {
    bool ret = chronoPINVOKE.ChParticleEventFlowInRectangle_TriggerEvent(swigCPtr, ChBody.getCPtr(mbody), ChSystem.getCPtr(msystem));
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void SetupPostProcess(ChSystem msystem) {
    chronoPINVOKE.ChParticleEventFlowInRectangle_SetupPostProcess(swigCPtr, ChSystem.getCPtr(msystem));
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  public double Xsize {
    set {
      chronoPINVOKE.ChParticleEventFlowInRectangle_Xsize_set(swigCPtr, value);
      if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = chronoPINVOKE.ChParticleEventFlowInRectangle_Xsize_get(swigCPtr);
      if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double Ysize {
    set {
      chronoPINVOKE.ChParticleEventFlowInRectangle_Ysize_set(swigCPtr, value);
      if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = chronoPINVOKE.ChParticleEventFlowInRectangle_Ysize_get(swigCPtr);
      if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double margin {
    set {
      chronoPINVOKE.ChParticleEventFlowInRectangle_margin_set(swigCPtr, value);
      if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = chronoPINVOKE.ChParticleEventFlowInRectangle_margin_get(swigCPtr);
      if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ChCoordsysd rectangle_csys {
    set {
      chronoPINVOKE.ChParticleEventFlowInRectangle_rectangle_csys_set(swigCPtr, ChCoordsysd.getCPtr(value));
      if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = chronoPINVOKE.ChParticleEventFlowInRectangle_rectangle_csys_get(swigCPtr);
      ChCoordsysd ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChCoordsysd(cPtr, false);
      if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ChVector3d last_intersectionUV {
    set {
      chronoPINVOKE.ChParticleEventFlowInRectangle_last_intersectionUV_set(swigCPtr, ChVector3d.getCPtr(value));
      if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = chronoPINVOKE.ChParticleEventFlowInRectangle_last_intersectionUV_get(swigCPtr);
      ChVector3d ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChVector3d(cPtr, false);
      if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}
