//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class chrono_vehicle {
  public static void SetDataPath(string path) {
    chrono_vehiclePINVOKE.SetDataPath(path);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public static string GetDataPath() {
    string ret = chrono_vehiclePINVOKE.GetDataPath();
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string GetDataFile(string filename) {
    string ret = chrono_vehiclePINVOKE.GetDataFile(filename);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_int new_intp() {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.new_intp();
    SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_int copy_intp(int value) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.copy_intp(value);
    SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void delete_intp(SWIGTYPE_p_int obj) {
    chrono_vehiclePINVOKE.delete_intp(SWIGTYPE_p_int.getCPtr(obj));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public static void intp_assign(SWIGTYPE_p_int obj, int value) {
    chrono_vehiclePINVOKE.intp_assign(SWIGTYPE_p_int.getCPtr(obj), value);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public static int intp_value(SWIGTYPE_p_int obj) {
    int ret = chrono_vehiclePINVOKE.intp_value(SWIGTYPE_p_int.getCPtr(obj));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_double new_doublep() {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.new_doublep();
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_double copy_doublep(double value) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.copy_doublep(value);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void delete_doublep(SWIGTYPE_p_double obj) {
    chrono_vehiclePINVOKE.delete_doublep(SWIGTYPE_p_double.getCPtr(obj));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public static void doublep_assign(SWIGTYPE_p_double obj, double value) {
    chrono_vehiclePINVOKE.doublep_assign(SWIGTYPE_p_double.getCPtr(obj), value);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public static double doublep_value(SWIGTYPE_p_double obj) {
    double ret = chrono_vehiclePINVOKE.doublep_value(SWIGTYPE_p_double.getCPtr(obj));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChBezierCurve StraightLinePath(ChVector3d start, ChVector3d end, uint num_intermediate) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.StraightLinePath__SWIG_0(ChVector3d.getCPtr(start), ChVector3d.getCPtr(end), num_intermediate);
    ChBezierCurve ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChBezierCurve(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChBezierCurve StraightLinePath(ChVector3d start, ChVector3d end) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.StraightLinePath__SWIG_1(ChVector3d.getCPtr(start), ChVector3d.getCPtr(end));
    ChBezierCurve ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChBezierCurve(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChBezierCurve CirclePath(ChVector3d start, double radius, double run, bool left_turn, int num_turns) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CirclePath__SWIG_0(ChVector3d.getCPtr(start), radius, run, left_turn, num_turns);
    ChBezierCurve ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChBezierCurve(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChBezierCurve CirclePath(ChVector3d start, double radius, double run, bool left_turn) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CirclePath__SWIG_1(ChVector3d.getCPtr(start), radius, run, left_turn);
    ChBezierCurve ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChBezierCurve(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChBezierCurve CirclePath(ChVector3d start, double radius, double run) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CirclePath__SWIG_2(ChVector3d.getCPtr(start), radius, run);
    ChBezierCurve ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChBezierCurve(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChBezierCurve DoubleLaneChangePath(ChVector3d start, double ramp, double width, double length, double run, bool left_turn) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.DoubleLaneChangePath__SWIG_0(ChVector3d.getCPtr(start), ramp, width, length, run, left_turn);
    ChBezierCurve ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChBezierCurve(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChBezierCurve DoubleLaneChangePath(ChVector3d start, double ramp, double width, double length, double run) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.DoubleLaneChangePath__SWIG_1(ChVector3d.getCPtr(start), ramp, width, length, run);
    ChBezierCurve ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChBezierCurve(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void ReadFileJSON(string filename, SWIGTYPE_p_rapidjson__Document d) {
    chrono_vehiclePINVOKE.ReadFileJSON(filename, SWIGTYPE_p_rapidjson__Document.getCPtr(d));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public static ChVector3d ReadVectorJSON(SWIGTYPE_p_rapidjson__Value a) {
    ChVector3d ret = new ChVector3d(chrono_vehiclePINVOKE.ReadVectorJSON(SWIGTYPE_p_rapidjson__Value.getCPtr(a)), true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChQuaterniond ReadQuaternionJSON(SWIGTYPE_p_rapidjson__Value a) {
    ChQuaterniond ret = new ChQuaterniond(chrono_vehiclePINVOKE.ReadQuaternionJSON(SWIGTYPE_p_rapidjson__Value.getCPtr(a)), true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChCoordsysd ReadCoordinateSystemJSON(SWIGTYPE_p_rapidjson__Value a) {
    ChCoordsysd ret = new ChCoordsysd(chrono_vehiclePINVOKE.ReadCoordinateSystemJSON(SWIGTYPE_p_rapidjson__Value.getCPtr(a)), true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChColor ReadColorJSON(SWIGTYPE_p_rapidjson__Value a) {
    ChColor ret = new ChColor(chrono_vehiclePINVOKE.ReadColorJSON(SWIGTYPE_p_rapidjson__Value.getCPtr(a)), true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChContactMaterialData ReadMaterialInfoJSON(SWIGTYPE_p_rapidjson__Value mat) {
    ChContactMaterialData ret = new ChContactMaterialData(chrono_vehiclePINVOKE.ReadMaterialInfoJSON(SWIGTYPE_p_rapidjson__Value.getCPtr(mat)), true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_std__shared_ptrT_chrono__vehicle__ChVehicleBushingData_t ReadBushingDataJSON(SWIGTYPE_p_rapidjson__Value bd) {
    SWIGTYPE_p_std__shared_ptrT_chrono__vehicle__ChVehicleBushingData_t ret = new SWIGTYPE_p_std__shared_ptrT_chrono__vehicle__ChVehicleBushingData_t(chrono_vehiclePINVOKE.ReadBushingDataJSON(SWIGTYPE_p_rapidjson__Value.getCPtr(bd)), true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChVehicleJoint.Type ReadVehicleJointTypeJSON(SWIGTYPE_p_rapidjson__Value a) {
    ChVehicleJoint.Type ret = (ChVehicleJoint.Type)chrono_vehiclePINVOKE.ReadVehicleJointTypeJSON(SWIGTYPE_p_rapidjson__Value.getCPtr(a));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChBodyGeometry ReadVehicleGeometryJSON(SWIGTYPE_p_rapidjson__Value d) {
    ChBodyGeometry ret = new ChBodyGeometry(chrono_vehiclePINVOKE.ReadVehicleGeometryJSON(SWIGTYPE_p_rapidjson__Value.getCPtr(d)), true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChTSDAGeometry ReadTSDAGeometryJSON(SWIGTYPE_p_rapidjson__Value d) {
    ChTSDAGeometry ret = new ChTSDAGeometry(chrono_vehiclePINVOKE.ReadTSDAGeometryJSON(SWIGTYPE_p_rapidjson__Value.getCPtr(d)), true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ForceFunctor ReadTSDAFunctorJSON(SWIGTYPE_p_rapidjson__Value td, SWIGTYPE_p_double free_length) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadTSDAFunctorJSON(SWIGTYPE_p_rapidjson__Value.getCPtr(td), SWIGTYPE_p_double.getCPtr(free_length));
    ForceFunctor ret = (cPtr == global::System.IntPtr.Zero) ? null : new ForceFunctor(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TorqueFunctor ReadRSDAFunctorJSON(SWIGTYPE_p_rapidjson__Value td, SWIGTYPE_p_double free_angle) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadRSDAFunctorJSON(SWIGTYPE_p_rapidjson__Value.getCPtr(td), SWIGTYPE_p_double.getCPtr(free_angle));
    TorqueFunctor ret = (cPtr == global::System.IntPtr.Zero) ? null : new TorqueFunctor(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChChassis ReadChassisJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadChassisJSON(filename);
    ChChassis ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChChassis(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChChassisRear ReadChassisRearJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadChassisRearJSON(filename);
    ChChassisRear ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChChassisRear(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChChassisConnector ReadChassisConnectorJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadChassisConnectorJSON(filename);
    ChChassisConnector ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChChassisConnector(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChEngine ReadEngineJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadEngineJSON(filename);
    ChEngine ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChEngine(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChTransmission ReadTransmissionJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadTransmissionJSON(filename);
    ChTransmission ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChTransmission(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChSuspension ReadSuspensionJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadSuspensionJSON(filename);
    ChSuspension ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChSuspension(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChSteering ReadSteeringJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadSteeringJSON(filename);
    ChSteering ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChSteering(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChDrivelineWV ReadDrivelineWVJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadDrivelineWVJSON(filename);
    ChDrivelineWV ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChDrivelineWV(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_std__shared_ptrT_ChAntirollBar_t ReadAntirollbarJSON(string filename) {
    SWIGTYPE_p_std__shared_ptrT_ChAntirollBar_t ret = new SWIGTYPE_p_std__shared_ptrT_ChAntirollBar_t(chrono_vehiclePINVOKE.ReadAntirollbarJSON(filename), true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChWheel ReadWheelJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadWheelJSON(filename);
    ChWheel ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChWheel(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChSubchassis ReadSubchassisJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadSubchassisJSON(filename);
    ChSubchassis ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChSubchassis(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChBrake ReadBrakeJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadBrakeJSON(filename);
    ChBrake ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChBrake(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChTire ReadTireJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadTireJSON(filename);
    ChTire ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChTire(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChTrackAssembly ReadTrackAssemblyJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadTrackAssemblyJSON(filename);
    ChTrackAssembly ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChTrackAssembly(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChDrivelineTV ReadDrivelineTVJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadDrivelineTVJSON(filename);
    ChDrivelineTV ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChDrivelineTV(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChTrackBrake ReadTrackBrakeJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadTrackBrakeJSON(filename);
    ChTrackBrake ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChTrackBrake(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChIdler ReadIdlerJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadIdlerJSON(filename);
    ChIdler ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChIdler(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChTrackSuspension ReadTrackSuspensionJSON(string filename, bool has_shock, bool lock_arm) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadTrackSuspensionJSON(filename, has_shock, lock_arm);
    ChTrackSuspension ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChTrackSuspension(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChTrackWheel ReadTrackWheelJSON(string filename) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.ReadTrackWheelJSON(filename);
    ChTrackWheel ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChTrackWheel(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChDoubleWishbone CastToChDoubleWishbone(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChDoubleWishbone(ChSuspension.getCPtr(in_obj));
    ChDoubleWishbone ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChDoubleWishbone(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChMacPhersonStrut CastToChMacPhersonStrut(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChMacPhersonStrut(ChSuspension.getCPtr(in_obj));
    ChMacPhersonStrut ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChMacPhersonStrut(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChLeafspringAxle CastToChLeafspringAxle(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChLeafspringAxle(ChSuspension.getCPtr(in_obj));
    ChLeafspringAxle ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChLeafspringAxle(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChHendricksonPRIMAXX CastToChHendricksonPRIMAXX(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChHendricksonPRIMAXX(ChSuspension.getCPtr(in_obj));
    ChHendricksonPRIMAXX ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChHendricksonPRIMAXX(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChDoubleWishboneReduced CastToChDoubleWishboneReduced(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChDoubleWishboneReduced(ChSuspension.getCPtr(in_obj));
    ChDoubleWishboneReduced ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChDoubleWishboneReduced(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChMultiLink CastToChMultiLink(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChMultiLink(ChSuspension.getCPtr(in_obj));
    ChMultiLink ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChMultiLink(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChRigidPinnedAxle CastToChRigidPinnedAxle(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChRigidPinnedAxle(ChSuspension.getCPtr(in_obj));
    ChRigidPinnedAxle ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChRigidPinnedAxle(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChSemiTrailingArm CastToChSemiTrailingArm(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChSemiTrailingArm(ChSuspension.getCPtr(in_obj));
    ChSemiTrailingArm ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChSemiTrailingArm(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChRigidSuspension CastToChRigidSuspension(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChRigidSuspension(ChSuspension.getCPtr(in_obj));
    ChRigidSuspension ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChRigidSuspension(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChSolidAxle CastToChSolidAxle(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChSolidAxle(ChSuspension.getCPtr(in_obj));
    ChSolidAxle ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChSolidAxle(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChThreeLinkIRS CastToChThreeLinkIRS(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChThreeLinkIRS(ChSuspension.getCPtr(in_obj));
    ChThreeLinkIRS ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChThreeLinkIRS(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChToeBarLeafspringAxle CastToChToeBarLeafspringAxle(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChToeBarLeafspringAxle(ChSuspension.getCPtr(in_obj));
    ChToeBarLeafspringAxle ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChToeBarLeafspringAxle(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChSolidBellcrankThreeLinkAxle CastToChSolidBellcrankThreeLinkAxle(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChSolidBellcrankThreeLinkAxle(ChSuspension.getCPtr(in_obj));
    ChSolidBellcrankThreeLinkAxle ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChSolidBellcrankThreeLinkAxle(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChSolidThreeLinkAxle CastToChSolidThreeLinkAxle(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChSolidThreeLinkAxle(ChSuspension.getCPtr(in_obj));
    ChSolidThreeLinkAxle ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChSolidThreeLinkAxle(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChSingleWishbone CastToChSingleWishbone(ChSuspension in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChSingleWishbone(ChSuspension.getCPtr(in_obj));
    ChSingleWishbone ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChSingleWishbone(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChPitmanArm CastToChPitmanArm(ChSteering in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChPitmanArm(ChSteering.getCPtr(in_obj));
    ChPitmanArm ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChPitmanArm(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChPitmanArmShafts CastToChPitmanArmShafts(ChSteering in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChPitmanArmShafts(ChSteering.getCPtr(in_obj));
    ChPitmanArmShafts ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChPitmanArmShafts(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChRackPinion CastToChRackPinion(ChSteering in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChRackPinion(ChSteering.getCPtr(in_obj));
    ChRackPinion ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChRackPinion(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChRotaryArm CastToChRotaryArm(ChSteering in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChRotaryArm(ChSteering.getCPtr(in_obj));
    ChRotaryArm ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChRotaryArm(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChRigidChassis CastToChRigidChassis(ChChassis in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChRigidChassis(ChChassis.getCPtr(in_obj));
    ChRigidChassis ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChRigidChassis(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChRigidChassisRear CastToChRigidChassisRear(ChChassisRear in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChRigidChassisRear(ChChassisRear.getCPtr(in_obj));
    ChRigidChassisRear ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChRigidChassisRear(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChChassisConnectorArticulated CastToChChassisConnectorArticulated(ChChassisConnector in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChChassisConnectorArticulated(ChChassisConnector.getCPtr(in_obj));
    ChChassisConnectorArticulated ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChChassisConnectorArticulated(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChChassisConnectorHitch CastToChChassisConnectorHitch(ChChassisConnector in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChChassisConnectorHitch(ChChassisConnector.getCPtr(in_obj));
    ChChassisConnectorHitch ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChChassisConnectorHitch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChChassisConnectorTorsion CastToChChassisConnectorTorsion(ChChassisConnector in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChChassisConnectorTorsion(ChChassisConnector.getCPtr(in_obj));
    ChChassisConnectorTorsion ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChChassisConnectorTorsion(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChBalancer CastToChBalancer(ChSubchassis in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChBalancer(ChSubchassis.getCPtr(in_obj));
    ChBalancer ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChBalancer(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChTMeasyTire CastToChTMeasyTire(ChTire in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChTMeasyTire(ChTire.getCPtr(in_obj));
    ChTMeasyTire ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChTMeasyTire(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChRigidTire CastToChRigidTire(ChTire in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChRigidTire(ChTire.getCPtr(in_obj));
    ChRigidTire ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChRigidTire(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_chrono__vehicle__ChReissnerTire CastToChReissnerTire(ChTire in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChReissnerTire(ChTire.getCPtr(in_obj));
    SWIGTYPE_p_chrono__vehicle__ChReissnerTire ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_chrono__vehicle__ChReissnerTire(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChPac89Tire CastToChPac89Tire(ChTire in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChPac89Tire(ChTire.getCPtr(in_obj));
    ChPac89Tire ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChPac89Tire(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChPac02Tire CastToChPac02Tire(ChTire in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChPac02Tire(ChTire.getCPtr(in_obj));
    ChPac02Tire ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChPac02Tire(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChFialaTire CastToChFialaTire(ChTire in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChFialaTire(ChTire.getCPtr(in_obj));
    ChFialaTire ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChFialaTire(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChEngineSimple CastToChEngineSimple(ChEngine in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChEngineSimple(ChEngine.getCPtr(in_obj));
    ChEngineSimple ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChEngineSimple(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChEngineSimpleMap CastToChEngineSimpleMap(ChEngine in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChEngineSimpleMap(ChEngine.getCPtr(in_obj));
    ChEngineSimpleMap ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChEngineSimpleMap(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChEngineShafts CastToChEngineShafts(ChEngine in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChEngineShafts(ChEngine.getCPtr(in_obj));
    ChEngineShafts ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChEngineShafts(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static EngineSimple CastToEngineSimple(ChEngine in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToEngineSimple(ChEngine.getCPtr(in_obj));
    EngineSimple ret = (cPtr == global::System.IntPtr.Zero) ? null : new EngineSimple(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static EngineSimpleMap CastToEngineSimpleMap(ChEngine in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToEngineSimpleMap(ChEngine.getCPtr(in_obj));
    EngineSimpleMap ret = (cPtr == global::System.IntPtr.Zero) ? null : new EngineSimpleMap(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static EngineShafts CastToEngineShafts(ChEngine in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToEngineShafts(ChEngine.getCPtr(in_obj));
    EngineShafts ret = (cPtr == global::System.IntPtr.Zero) ? null : new EngineShafts(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChAutomaticTransmissionSimpleMap CastToChAutomaticTransmissionSimpleMap(ChTransmission in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChAutomaticTransmissionSimpleMap__SWIG_0(ChTransmission.getCPtr(in_obj));
    ChAutomaticTransmissionSimpleMap ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChAutomaticTransmissionSimpleMap(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChAutomaticTransmissionShafts CastToChAutomaticTransmissionShafts(ChTransmission in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChAutomaticTransmissionShafts__SWIG_0(ChTransmission.getCPtr(in_obj));
    ChAutomaticTransmissionShafts ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChAutomaticTransmissionShafts(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static AutomaticTransmissionSimpleMap CastToAutomaticTransmissionSimpleMap(ChTransmission in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToAutomaticTransmissionSimpleMap(ChTransmission.getCPtr(in_obj));
    AutomaticTransmissionSimpleMap ret = (cPtr == global::System.IntPtr.Zero) ? null : new AutomaticTransmissionSimpleMap(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static AutomaticTransmissionShafts CastToAutomaticTransmissionShafts(ChTransmission in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToAutomaticTransmissionShafts(ChTransmission.getCPtr(in_obj));
    AutomaticTransmissionShafts ret = (cPtr == global::System.IntPtr.Zero) ? null : new AutomaticTransmissionShafts(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChManualTransmissionShafts CastToChManualTransmissionShafts(ChTransmission in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChManualTransmissionShafts__SWIG_0(ChTransmission.getCPtr(in_obj));
    ChManualTransmissionShafts ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChManualTransmissionShafts(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ManualTransmissionShafts CastToManualTransmissionShafts(ChTransmission in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToManualTransmissionShafts(ChTransmission.getCPtr(in_obj));
    ManualTransmissionShafts ret = (cPtr == global::System.IntPtr.Zero) ? null : new ManualTransmissionShafts(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChAutomaticTransmission CastToChAutomaticTransmission(ChTransmission in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChAutomaticTransmission(ChTransmission.getCPtr(in_obj));
    ChAutomaticTransmission ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChAutomaticTransmission(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChAutomaticTransmissionSimpleMap CastToChAutomaticTransmissionSimpleMap(ChAutomaticTransmission in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChAutomaticTransmissionSimpleMap__SWIG_1(ChAutomaticTransmission.getCPtr(in_obj));
    ChAutomaticTransmissionSimpleMap ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChAutomaticTransmissionSimpleMap(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChAutomaticTransmissionShafts CastToChAutomaticTransmissionShafts(ChAutomaticTransmission in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChAutomaticTransmissionShafts__SWIG_1(ChAutomaticTransmission.getCPtr(in_obj));
    ChAutomaticTransmissionShafts ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChAutomaticTransmissionShafts(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChManualTransmission CastToChManualTransmission(ChTransmission in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChManualTransmission(ChTransmission.getCPtr(in_obj));
    ChManualTransmission ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChManualTransmission(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChManualTransmissionShafts CastToChManualTransmissionShafts(ChManualTransmission in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChManualTransmissionShafts__SWIG_1(ChManualTransmission.getCPtr(in_obj));
    ChManualTransmissionShafts ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChManualTransmissionShafts(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChDrivelineWV CastToChDrivelineWV(ChDriveline in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChDrivelineWV(ChDriveline.getCPtr(in_obj));
    ChDrivelineWV ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChDrivelineWV(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChShaftsDriveline2WD CastToChShaftsDriveline2WD(ChDriveline in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChShaftsDriveline2WD(ChDriveline.getCPtr(in_obj));
    ChShaftsDriveline2WD ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChShaftsDriveline2WD(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChShaftsDriveline4WD CastToChShaftsDriveline4WD(ChDriveline in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChShaftsDriveline4WD(ChDriveline.getCPtr(in_obj));
    ChShaftsDriveline4WD ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChShaftsDriveline4WD(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChSimpleDriveline CastToChSimpleDriveline(ChDriveline in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChSimpleDriveline(ChDriveline.getCPtr(in_obj));
    ChSimpleDriveline ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChSimpleDriveline(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ChSimpleDrivelineXWD CastToChSimpleDrivelineXWD(ChDriveline in_obj) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.CastToChSimpleDrivelineXWD(ChDriveline.getCPtr(in_obj));
    ChSimpleDrivelineXWD ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChSimpleDrivelineXWD(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
