//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ChVoightTensorD : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ChVoightTensorD(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChVoightTensorD obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ChVoightTensorD() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          chronoPINVOKE.delete_ChVoightTensorD(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ChVoightTensorD() : this(chronoPINVOKE.new_ChVoightTensorD(), true) {
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetVolumetricPart() {
    double ret = chronoPINVOKE.ChVoightTensorD_GetVolumetricPart(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void GetDeviatoricPart(ChVoightTensorD mdeviatoric) {
    chronoPINVOKE.ChVoightTensorD_GetDeviatoricPart(swigCPtr, ChVoightTensorD.getCPtr(mdeviatoric));
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetInvariant_I1() {
    double ret = chronoPINVOKE.ChVoightTensorD_GetInvariant_I1(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetInvariant_I2() {
    double ret = chronoPINVOKE.ChVoightTensorD_GetInvariant_I2(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetInvariant_I3() {
    double ret = chronoPINVOKE.ChVoightTensorD_GetInvariant_I3(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetInvariant_J1() {
    double ret = chronoPINVOKE.ChVoightTensorD_GetInvariant_J1(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetInvariant_J2() {
    double ret = chronoPINVOKE.ChVoightTensorD_GetInvariant_J2(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetInvariant_J3() {
    double ret = chronoPINVOKE.ChVoightTensorD_GetInvariant_J3(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Rotate(SWIGTYPE_p_ChMatrix33T_double_t Rot) {
    chronoPINVOKE.ChVoightTensorD_Rotate(swigCPtr, SWIGTYPE_p_ChMatrix33T_double_t.getCPtr(Rot));
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ComputeEigenvalues(SWIGTYPE_p_double e1, SWIGTYPE_p_double e2, SWIGTYPE_p_double e3) {
    chronoPINVOKE.ChVoightTensorD_ComputeEigenvalues(swigCPtr, SWIGTYPE_p_double.getCPtr(e1), SWIGTYPE_p_double.getCPtr(e2), SWIGTYPE_p_double.getCPtr(e3));
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ComputeEigenvectors(SWIGTYPE_p_double eigval1, SWIGTYPE_p_double eigval2, SWIGTYPE_p_double eigval3, ChVector3d eigvector1, ChVector3d eigvector2, ChVector3d eigvector3) {
    chronoPINVOKE.ChVoightTensorD_ComputeEigenvectors(swigCPtr, SWIGTYPE_p_double.getCPtr(eigval1), SWIGTYPE_p_double.getCPtr(eigval2), SWIGTYPE_p_double.getCPtr(eigval3), ChVector3d.getCPtr(eigvector1), ChVector3d.getCPtr(eigvector2), ChVector3d.getCPtr(eigvector3));
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetEquivalentVonMises() {
    double ret = chronoPINVOKE.ChVoightTensorD_GetEquivalentVonMises(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetEquivalentMeanHydrostatic() {
    double ret = chronoPINVOKE.ChVoightTensorD_GetEquivalentMeanHydrostatic(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetEquivalentOctahedralNormal() {
    double ret = chronoPINVOKE.ChVoightTensorD_GetEquivalentOctahedralNormal(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetEquivalentOctahedralDeviatoric() {
    double ret = chronoPINVOKE.ChVoightTensorD_GetEquivalentOctahedralDeviatoric(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double XX() {
    double ret = chronoPINVOKE.ChVoightTensorD_XX(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double YY() {
    double ret = chronoPINVOKE.ChVoightTensorD_YY(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double ZZ() {
    double ret = chronoPINVOKE.ChVoightTensorD_ZZ(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double XY() {
    double ret = chronoPINVOKE.ChVoightTensorD_XY(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double XZ() {
    double ret = chronoPINVOKE.ChVoightTensorD_XZ(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double YZ() {
    double ret = chronoPINVOKE.ChVoightTensorD_YZ(swigCPtr);
    if (chronoPINVOKE.SWIGPendingException.Pending) throw chronoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
