//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class M113_TrackShoeDoublePin : ChTrackShoeDoublePin {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal M113_TrackShoeDoublePin(global::System.IntPtr cPtr, bool cMemoryOwn) : base(chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(M113_TrackShoeDoublePin obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          chrono_vehiclePINVOKE.delete_M113_TrackShoeDoublePin(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public M113_TrackShoeDoublePin(string name, DoublePinTrackShoeType topology) : this(chrono_vehiclePINVOKE.new_M113_TrackShoeDoublePin(name, (int)topology), true) {
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual new GuidePinType GetType() {
    GuidePinType ret = (GuidePinType)chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetType(swigCPtr);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override double GetHeight() {
    double ret = chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetHeight(swigCPtr);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetShoeMass() {
    double ret = chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetShoeMass(swigCPtr);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual ChVector3d GetShoeInertia() {
    ChVector3d ret = new ChVector3d(chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetShoeInertia(swigCPtr), false);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetShoeLength() {
    double ret = chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetShoeLength(swigCPtr);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetShoeWidth() {
    double ret = chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetShoeWidth(swigCPtr);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override ChVector3d GetLateralContactPoint() {
    ChVector3d ret = new ChVector3d(chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetLateralContactPoint(swigCPtr), true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetConnectorMass() {
    double ret = chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetConnectorMass(swigCPtr);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual ChVector3d GetConnectorInertia() {
    ChVector3d ret = new ChVector3d(chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetConnectorInertia(swigCPtr), false);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetConnectorLength() {
    double ret = chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetConnectorLength(swigCPtr);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetConnectorRadius() {
    double ret = chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetConnectorRadius(swigCPtr);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetConnectorWidth() {
    double ret = chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetConnectorWidth(swigCPtr);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override ChBodyGeometry GetGroundContactGeometry() {
    ChBodyGeometry ret = new ChBodyGeometry(chrono_vehiclePINVOKE.M113_TrackShoeDoublePin_GetGroundContactGeometry(swigCPtr), true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
