//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class RigidTerrain : ChTerrain {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal RigidTerrain(global::System.IntPtr cPtr, bool cMemoryOwn) : base(chrono_vehiclePINVOKE.RigidTerrain_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RigidTerrain obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          chrono_vehiclePINVOKE.delete_RigidTerrain(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public RigidTerrain(ChSystem system) : this(chrono_vehiclePINVOKE.new_RigidTerrain__SWIG_0(ChSystem.getCPtr(system)), true) {
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public RigidTerrain(ChSystem system, string filename) : this(chrono_vehiclePINVOKE.new_RigidTerrain__SWIG_1(ChSystem.getCPtr(system), filename), true) {
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, double length, double width, double thickness, bool tiled, double max_tile_size, bool visualization) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_0(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), length, width, thickness, tiled, max_tile_size, visualization);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, double length, double width, double thickness, bool tiled, double max_tile_size) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_1(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), length, width, thickness, tiled, max_tile_size);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, double length, double width, double thickness, bool tiled) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_2(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), length, width, thickness, tiled);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, double length, double width, double thickness) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_3(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), length, width, thickness);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, double length, double width) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_4(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), length, width);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, string mesh_file, bool connected_mesh, double sweep_sphere_radius, bool visualization) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_5(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), mesh_file, connected_mesh, sweep_sphere_radius, visualization);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, string mesh_file, bool connected_mesh, double sweep_sphere_radius) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_6(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), mesh_file, connected_mesh, sweep_sphere_radius);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, string mesh_file, bool connected_mesh) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_7(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), mesh_file, connected_mesh);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, string mesh_file) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_8(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), mesh_file);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, string heightmap_file, double length, double width, double hMin, double hMax, bool connected_mesh, double sweep_sphere_radius, bool visualization) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_9(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), heightmap_file, length, width, hMin, hMax, connected_mesh, sweep_sphere_radius, visualization);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, string heightmap_file, double length, double width, double hMin, double hMax, bool connected_mesh, double sweep_sphere_radius) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_10(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), heightmap_file, length, width, hMin, hMax, connected_mesh, sweep_sphere_radius);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, string heightmap_file, double length, double width, double hMin, double hMax, bool connected_mesh) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_11(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), heightmap_file, length, width, hMin, hMax, connected_mesh);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, string heightmap_file, double length, double width, double hMin, double hMax) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_12(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), heightmap_file, length, width, hMin, hMax);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, vector_ChVector3d point_cloud, double length, double width, int unrefined_resolution, int heightmap_resolution, int max_refinements, double refine_angle_limit, double smoothing_factor, double max_edge_length, double sweep_sphere_radius, bool visualization) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_13(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), vector_ChVector3d.getCPtr(point_cloud), length, width, unrefined_resolution, heightmap_resolution, max_refinements, refine_angle_limit, smoothing_factor, max_edge_length, sweep_sphere_radius, visualization);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, vector_ChVector3d point_cloud, double length, double width, int unrefined_resolution, int heightmap_resolution, int max_refinements, double refine_angle_limit, double smoothing_factor, double max_edge_length, double sweep_sphere_radius) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_14(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), vector_ChVector3d.getCPtr(point_cloud), length, width, unrefined_resolution, heightmap_resolution, max_refinements, refine_angle_limit, smoothing_factor, max_edge_length, sweep_sphere_radius);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, vector_ChVector3d point_cloud, double length, double width, int unrefined_resolution, int heightmap_resolution, int max_refinements, double refine_angle_limit, double smoothing_factor, double max_edge_length) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_15(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), vector_ChVector3d.getCPtr(point_cloud), length, width, unrefined_resolution, heightmap_resolution, max_refinements, refine_angle_limit, smoothing_factor, max_edge_length);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, vector_ChVector3d point_cloud, double length, double width, int unrefined_resolution, int heightmap_resolution, int max_refinements, double refine_angle_limit, double smoothing_factor) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_16(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), vector_ChVector3d.getCPtr(point_cloud), length, width, unrefined_resolution, heightmap_resolution, max_refinements, refine_angle_limit, smoothing_factor);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, vector_ChVector3d point_cloud, double length, double width, int unrefined_resolution, int heightmap_resolution, int max_refinements, double refine_angle_limit) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_17(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), vector_ChVector3d.getCPtr(point_cloud), length, width, unrefined_resolution, heightmap_resolution, max_refinements, refine_angle_limit);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, vector_ChVector3d point_cloud, double length, double width, int unrefined_resolution, int heightmap_resolution, int max_refinements) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_18(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), vector_ChVector3d.getCPtr(point_cloud), length, width, unrefined_resolution, heightmap_resolution, max_refinements);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Patch AddPatch(ChContactMaterial material, ChCoordsysd position, vector_ChVector3d point_cloud, double length, double width, int unrefined_resolution, int heightmap_resolution) {
    global::System.IntPtr cPtr = chrono_vehiclePINVOKE.RigidTerrain_AddPatch__SWIG_19(swigCPtr, ChContactMaterial.getCPtr(material), ChCoordsysd.getCPtr(position), vector_ChVector3d.getCPtr(point_cloud), length, width, unrefined_resolution, heightmap_resolution);
    Patch ret = (cPtr == global::System.IntPtr.Zero) ? null : new Patch(cPtr, true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Initialize() {
    chrono_vehiclePINVOKE.RigidTerrain_Initialize(swigCPtr);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public ChPatchList GetPatches() {
    ChPatchList ret = new ChPatchList(chrono_vehiclePINVOKE.RigidTerrain_GetPatches(swigCPtr), false);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void BindPatch(Patch patch) {
    chrono_vehiclePINVOKE.RigidTerrain_BindPatch(swigCPtr, Patch.getCPtr(patch));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemovePatch(Patch patch) {
    chrono_vehiclePINVOKE.RigidTerrain_RemovePatch(swigCPtr, Patch.getCPtr(patch));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseLocationDependentFriction(bool val) {
    chrono_vehiclePINVOKE.RigidTerrain_UseLocationDependentFriction(swigCPtr, val);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public override double GetHeight(ChVector3d loc) {
    double ret = chrono_vehiclePINVOKE.RigidTerrain_GetHeight(swigCPtr, ChVector3d.getCPtr(loc));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override ChVector3d GetNormal(ChVector3d loc) {
    ChVector3d ret = new ChVector3d(chrono_vehiclePINVOKE.RigidTerrain_GetNormal(swigCPtr, ChVector3d.getCPtr(loc)), true);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override float GetCoefficientFriction(ChVector3d loc) {
    float ret = chrono_vehiclePINVOKE.RigidTerrain_GetCoefficientFriction(swigCPtr, ChVector3d.getCPtr(loc));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void GetProperties(ChVector3d loc, SWIGTYPE_p_double height, ChVector3d normal, SWIGTYPE_p_float friction) {
    chrono_vehiclePINVOKE.RigidTerrain_GetProperties(swigCPtr, ChVector3d.getCPtr(loc), SWIGTYPE_p_double.getCPtr(height), ChVector3d.getCPtr(normal), SWIGTYPE_p_float.getCPtr(friction));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public void ExportMeshPovray(string out_dir, bool smoothed) {
    chrono_vehiclePINVOKE.RigidTerrain_ExportMeshPovray__SWIG_0(swigCPtr, out_dir, smoothed);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public void ExportMeshPovray(string out_dir) {
    chrono_vehiclePINVOKE.RigidTerrain_ExportMeshPovray__SWIG_1(swigCPtr, out_dir);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public void ExportMeshWavefront(string out_dir) {
    chrono_vehiclePINVOKE.RigidTerrain_ExportMeshWavefront(swigCPtr, out_dir);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool FindPoint(ChVector3d loc, SWIGTYPE_p_double height, ChVector3d normal, SWIGTYPE_p_float friction) {
    bool ret = chrono_vehiclePINVOKE.RigidTerrain_FindPoint(swigCPtr, ChVector3d.getCPtr(loc), SWIGTYPE_p_double.getCPtr(height), ChVector3d.getCPtr(normal), SWIGTYPE_p_float.getCPtr(friction));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetCollisionFamily(int family) {
    chrono_vehiclePINVOKE.RigidTerrain_SetCollisionFamily(swigCPtr, family);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public enum PatchType {
    BOX,
    MESH,
    HEIGHT_MAP
  }

}
