//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TrackedVehicle : ChTrackedVehicle {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal TrackedVehicle(global::System.IntPtr cPtr, bool cMemoryOwn) : base(chrono_vehiclePINVOKE.TrackedVehicle_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TrackedVehicle obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          chrono_vehiclePINVOKE.delete_TrackedVehicle(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public TrackedVehicle(string filename, ChContactMethod contact_method) : this(chrono_vehiclePINVOKE.new_TrackedVehicle__SWIG_0(filename, (int)contact_method), true) {
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public TrackedVehicle(string filename) : this(chrono_vehiclePINVOKE.new_TrackedVehicle__SWIG_1(filename), true) {
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public TrackedVehicle(ChSystem system, string filename) : this(chrono_vehiclePINVOKE.new_TrackedVehicle__SWIG_2(ChSystem.getCPtr(system), filename), true) {
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void Initialize(ChCoordsysd chassisPos, double chassisFwdVel) {
    chrono_vehiclePINVOKE.TrackedVehicle_Initialize__SWIG_0(swigCPtr, ChCoordsysd.getCPtr(chassisPos), chassisFwdVel);
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void Initialize(ChCoordsysd chassisPos) {
    chrono_vehiclePINVOKE.TrackedVehicle_Initialize__SWIG_1(swigCPtr, ChCoordsysd.getCPtr(chassisPos));
    if (chrono_vehiclePINVOKE.SWIGPendingException.Pending) throw chrono_vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

}
